//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/Marlin/MarlinCompiler/src\MarlinParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MarlinCompiler.Antlr {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="MarlinParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IMarlinParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFile([NotNull] MarlinParser.FileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.typeName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeName([NotNull] MarlinParser.TypeNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.moduleName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModuleName([NotNull] MarlinParser.ModuleNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.modifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitModifier([NotNull] MarlinParser.ModifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.expectArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpectArgs([NotNull] MarlinParser.ExpectArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.expectArg"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpectArg([NotNull] MarlinParser.ExpectArgContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.giveArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGiveArgs([NotNull] MarlinParser.GiveArgsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] MarlinParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] MarlinParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.typeDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeDeclaration([NotNull] MarlinParser.TypeDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.classDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDeclaration([NotNull] MarlinParser.ClassDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.structDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDeclaration([NotNull] MarlinParser.StructDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.methodDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodDeclaration([NotNull] MarlinParser.MethodDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.methodCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodCall([NotNull] MarlinParser.MethodCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableDeclaration([NotNull] MarlinParser.VariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.localVariableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLocalVariableDeclaration([NotNull] MarlinParser.LocalVariableDeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.variableAssignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableAssignment([NotNull] MarlinParser.VariableAssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.memberAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMemberAccess([NotNull] MarlinParser.MemberAccessContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.arrayInitializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArrayInitializer([NotNull] MarlinParser.ArrayInitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.nativeCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNativeCall([NotNull] MarlinParser.NativeCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.return"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturn([NotNull] MarlinParser.ReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.classMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassMember([NotNull] MarlinParser.ClassMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.structMember"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructMember([NotNull] MarlinParser.StructMemberContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.methodBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMethodBody([NotNull] MarlinParser.MethodBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.booleanLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanLiteral([NotNull] MarlinParser.BooleanLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.stringLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringLiteral([NotNull] MarlinParser.StringLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.characterLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharacterLiteral([NotNull] MarlinParser.CharacterLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="MarlinParser.numberLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumberLiteral([NotNull] MarlinParser.NumberLiteralContext context);
}
} // namespace MarlinCompiler.Antlr
