//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/Projects/Marlin/MarlinCompiler/src\MarlinParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MarlinCompiler.Antlr {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class MarlinParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		WHITESPACES=1, MODULE=2, CLASS=3, STRUCT=4, RETURN=5, NEW=6, NATIVE=7, 
		NULL=8, TRUE=9, FALSE=10, PRIVATE=11, INTERNAL=12, PUBLIC=13, STATIC=14, 
		READONLY=15, SEALED=16, AT=17, DOT=18, COMMA=19, COLON=20, SEMICOLON=21, 
		LBRACE=22, RBRACE=23, LPAREN=24, RPAREN=25, LBRACKET=26, RBRACKET=27, 
		ASSIGN=28, QUOTE=29, DOUBLE_QUOTE=30, DOUBLE_COLON=31, ARROW=32, IDENTIFIER=33, 
		INTEGER=34, NORMAL_STRING=35, CHARACTER=36, DOUBLE=37;
	public const int
		RULE_file = 0, RULE_typeName = 1, RULE_moduleName = 2, RULE_modifier = 3, 
		RULE_expectArgs = 4, RULE_expectArg = 5, RULE_giveArgs = 6, RULE_statement = 7, 
		RULE_expression = 8, RULE_typeDeclaration = 9, RULE_classDeclaration = 10, 
		RULE_structDeclaration = 11, RULE_methodDeclaration = 12, RULE_methodCall = 13, 
		RULE_variableDeclaration = 14, RULE_localVariableDeclaration = 15, RULE_variableAssignment = 16, 
		RULE_memberAccess = 17, RULE_arrayInitializer = 18, RULE_nativeCall = 19, 
		RULE_return = 20, RULE_classMember = 21, RULE_structMember = 22, RULE_methodBody = 23, 
		RULE_booleanLiteral = 24, RULE_stringLiteral = 25, RULE_characterLiteral = 26, 
		RULE_numberLiteral = 27, RULE_nullLiteral = 28;
	public static readonly string[] ruleNames = {
		"file", "typeName", "moduleName", "modifier", "expectArgs", "expectArg", 
		"giveArgs", "statement", "expression", "typeDeclaration", "classDeclaration", 
		"structDeclaration", "methodDeclaration", "methodCall", "variableDeclaration", 
		"localVariableDeclaration", "variableAssignment", "memberAccess", "arrayInitializer", 
		"nativeCall", "return", "classMember", "structMember", "methodBody", "booleanLiteral", 
		"stringLiteral", "characterLiteral", "numberLiteral", "nullLiteral"
	};

	private static readonly string[] _LiteralNames = {
		null, null, "'module'", "'class'", "'struct'", "'return'", "'new'", "'native'", 
		"'null'", "'true'", "'false'", "'private'", "'internal'", "'public'", 
		"'static'", "'readonly'", "'sealed'", "'@'", "'.'", "','", "':'", "';'", 
		"'{'", "'}'", "'('", "')'", "'['", "']'", "'='", "'''", "'\"'", "'::'", 
		"'=>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "WHITESPACES", "MODULE", "CLASS", "STRUCT", "RETURN", "NEW", "NATIVE", 
		"NULL", "TRUE", "FALSE", "PRIVATE", "INTERNAL", "PUBLIC", "STATIC", "READONLY", 
		"SEALED", "AT", "DOT", "COMMA", "COLON", "SEMICOLON", "LBRACE", "RBRACE", 
		"LPAREN", "RPAREN", "LBRACKET", "RBRACKET", "ASSIGN", "QUOTE", "DOUBLE_QUOTE", 
		"DOUBLE_COLON", "ARROW", "IDENTIFIER", "INTEGER", "NORMAL_STRING", "CHARACTER", 
		"DOUBLE"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "MarlinParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static MarlinParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public MarlinParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public MarlinParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class FileContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(MarlinParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ModuleNameContext moduleName() {
			return GetRuleContext<ModuleNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeDeclarationContext[] typeDeclaration() {
			return GetRuleContexts<TypeDeclarationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeDeclarationContext typeDeclaration(int i) {
			return GetRuleContext<TypeDeclarationContext>(i);
		}
		public FileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_file; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFile(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FileContext file() {
		FileContext _localctx = new FileContext(Context, State);
		EnterRule(_localctx, 0, RULE_file);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 65;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==MODULE) {
				{
				State = 58;
				moduleName();
				State = 62;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << CLASS) | (1L << STRUCT) | (1L << PRIVATE) | (1L << INTERNAL) | (1L << PUBLIC) | (1L << STATIC) | (1L << READONLY) | (1L << SEALED))) != 0)) {
					{
					{
					State = 59;
					typeDeclaration();
					}
					}
					State = 64;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 67;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENTIFIER() { return GetTokens(MarlinParser.IDENTIFIER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER(int i) {
			return GetToken(MarlinParser.IDENTIFIER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DOUBLE_COLON() { return GetTokens(MarlinParser.DOUBLE_COLON); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE_COLON(int i) {
			return GetToken(MarlinParser.DOUBLE_COLON, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACKET() { return GetToken(MarlinParser.LBRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACKET() { return GetToken(MarlinParser.RBRACKET, 0); }
		public TypeNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeNameContext typeName() {
		return typeName(0);
	}

	private TypeNameContext typeName(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		TypeNameContext _localctx = new TypeNameContext(Context, _parentState);
		TypeNameContext _prevctx = _localctx;
		int _startState = 2;
		EnterRecursionRule(_localctx, 2, RULE_typeName, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 70;
			Match(IDENTIFIER);
			State = 75;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 71;
					Match(DOUBLE_COLON);
					State = 72;
					Match(IDENTIFIER);
					}
					} 
				}
				State = 77;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			}
			}
			Context.Stop = TokenStream.LT(-1);
			State = 83;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new TypeNameContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_typeName);
					State = 78;
					if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
					State = 79;
					Match(LBRACKET);
					State = 80;
					Match(RBRACKET);
					}
					} 
				}
				State = 85;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ModuleNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MODULE() { return GetToken(MarlinParser.MODULE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(MarlinParser.SEMICOLON, 0); }
		public ModuleNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_moduleName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitModuleName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ModuleNameContext moduleName() {
		ModuleNameContext _localctx = new ModuleNameContext(Context, State);
		EnterRule(_localctx, 4, RULE_moduleName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 86;
			Match(MODULE);
			State = 87;
			typeName(0);
			State = 88;
			Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ModifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PRIVATE() { return GetToken(MarlinParser.PRIVATE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PUBLIC() { return GetToken(MarlinParser.PUBLIC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTERNAL() { return GetToken(MarlinParser.INTERNAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STATIC() { return GetToken(MarlinParser.STATIC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode READONLY() { return GetToken(MarlinParser.READONLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEALED() { return GetToken(MarlinParser.SEALED, 0); }
		public ModifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_modifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitModifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ModifierContext modifier() {
		ModifierContext _localctx = new ModifierContext(Context, State);
		EnterRule(_localctx, 6, RULE_modifier);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 90;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PRIVATE) | (1L << INTERNAL) | (1L << PUBLIC) | (1L << STATIC) | (1L << READONLY) | (1L << SEALED))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpectArgsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(MarlinParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(MarlinParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpectArgContext[] expectArg() {
			return GetRuleContexts<ExpectArgContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpectArgContext expectArg(int i) {
			return GetRuleContext<ExpectArgContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(MarlinParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(MarlinParser.COMMA, i);
		}
		public ExpectArgsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expectArgs; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpectArgs(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpectArgsContext expectArgs() {
		ExpectArgsContext _localctx = new ExpectArgsContext(Context, State);
		EnterRule(_localctx, 8, RULE_expectArgs);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 92;
			Match(LPAREN);
			State = 101;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==IDENTIFIER) {
				{
				State = 93;
				expectArg();
				State = 98;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 94;
					Match(COMMA);
					State = 95;
					expectArg();
					}
					}
					State = 100;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 103;
			Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpectArgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(MarlinParser.IDENTIFIER, 0); }
		public ExpectArgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expectArg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpectArg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpectArgContext expectArg() {
		ExpectArgContext _localctx = new ExpectArgContext(Context, State);
		EnterRule(_localctx, 10, RULE_expectArg);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 105;
			typeName(0);
			State = 106;
			Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GiveArgsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(MarlinParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(MarlinParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(MarlinParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(MarlinParser.COMMA, i);
		}
		public GiveArgsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_giveArgs; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGiveArgs(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public GiveArgsContext giveArgs() {
		GiveArgsContext _localctx = new GiveArgsContext(Context, State);
		EnterRule(_localctx, 12, RULE_giveArgs);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 108;
			Match(LPAREN);
			State = 117;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << NEW) | (1L << NULL) | (1L << TRUE) | (1L << FALSE) | (1L << AT) | (1L << LPAREN) | (1L << IDENTIFIER) | (1L << INTEGER) | (1L << NORMAL_STRING) | (1L << CHARACTER) | (1L << DOUBLE))) != 0)) {
				{
				State = 109;
				expression();
				State = 114;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 110;
					Match(COMMA);
					State = 111;
					expression();
					}
					}
					State = 116;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 119;
			Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public MethodCallContext methodCall() {
			return GetRuleContext<MethodCallContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(MarlinParser.SEMICOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LocalVariableDeclarationContext localVariableDeclaration() {
			return GetRuleContext<LocalVariableDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VariableAssignmentContext variableAssignment() {
			return GetRuleContext<VariableAssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ReturnContext @return() {
			return GetRuleContext<ReturnContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NativeCallContext nativeCall() {
			return GetRuleContext<NativeCallContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 14, RULE_statement);
		try {
			State = 136;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 121;
				methodCall();
				State = 122;
				Match(SEMICOLON);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 124;
				localVariableDeclaration();
				State = 125;
				Match(SEMICOLON);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 127;
				variableAssignment();
				State = 128;
				Match(SEMICOLON);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 130;
				@return();
				State = 131;
				Match(SEMICOLON);
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 133;
				nativeCall();
				State = 134;
				Match(SEMICOLON);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(MarlinParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(MarlinParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public MethodCallContext methodCall() {
			return GetRuleContext<MethodCallContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemberAccessContext memberAccess() {
			return GetRuleContext<MemberAccessContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NullLiteralContext nullLiteral() {
			return GetRuleContext<NullLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BooleanLiteralContext booleanLiteral() {
			return GetRuleContext<BooleanLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringLiteralContext stringLiteral() {
			return GetRuleContext<StringLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public CharacterLiteralContext characterLiteral() {
			return GetRuleContext<CharacterLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberLiteralContext numberLiteral() {
			return GetRuleContext<NumberLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArrayInitializerContext arrayInitializer() {
			return GetRuleContext<ArrayInitializerContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NativeCallContext nativeCall() {
			return GetRuleContext<NativeCallContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 16, RULE_expression);
		try {
			State = 151;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 138;
				Match(LPAREN);
				State = 139;
				expression();
				State = 140;
				Match(RPAREN);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 142;
				methodCall();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 143;
				memberAccess(0);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 144;
				nullLiteral();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 145;
				booleanLiteral();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 146;
				stringLiteral();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 147;
				characterLiteral();
				}
				break;
			case 8:
				EnterOuterAlt(_localctx, 8);
				{
				State = 148;
				numberLiteral();
				}
				break;
			case 9:
				EnterOuterAlt(_localctx, 9);
				{
				State = 149;
				arrayInitializer();
				}
				break;
			case 10:
				EnterOuterAlt(_localctx, 10);
				{
				State = 150;
				nativeCall();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ClassDeclarationContext classDeclaration() {
			return GetRuleContext<ClassDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StructDeclarationContext structDeclaration() {
			return GetRuleContext<StructDeclarationContext>(0);
		}
		public TypeDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeDeclarationContext typeDeclaration() {
		TypeDeclarationContext _localctx = new TypeDeclarationContext(Context, State);
		EnterRule(_localctx, 18, RULE_typeDeclaration);
		try {
			State = 155;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 153;
				classDeclaration();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 154;
				structDeclaration();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClassDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLASS() { return GetToken(MarlinParser.CLASS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(MarlinParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(MarlinParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(MarlinParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ModifierContext[] modifier() {
			return GetRuleContexts<ModifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ModifierContext modifier(int i) {
			return GetRuleContext<ModifierContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(MarlinParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext[] typeName() {
			return GetRuleContexts<TypeNameContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName(int i) {
			return GetRuleContext<TypeNameContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ClassMemberContext[] classMember() {
			return GetRuleContexts<ClassMemberContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ClassMemberContext classMember(int i) {
			return GetRuleContext<ClassMemberContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(MarlinParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(MarlinParser.COMMA, i);
		}
		public ClassDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_classDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClassDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ClassDeclarationContext classDeclaration() {
		ClassDeclarationContext _localctx = new ClassDeclarationContext(Context, State);
		EnterRule(_localctx, 20, RULE_classDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 160;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PRIVATE) | (1L << INTERNAL) | (1L << PUBLIC) | (1L << STATIC) | (1L << READONLY) | (1L << SEALED))) != 0)) {
				{
				{
				State = 157;
				modifier();
				}
				}
				State = 162;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 163;
			Match(CLASS);
			State = 164;
			Match(IDENTIFIER);
			State = 174;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==COLON) {
				{
				State = 165;
				Match(COLON);
				State = 166;
				typeName(0);
				State = 171;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 167;
					Match(COMMA);
					State = 168;
					typeName(0);
					}
					}
					State = 173;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 176;
			Match(LBRACE);
			State = 180;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PRIVATE) | (1L << INTERNAL) | (1L << PUBLIC) | (1L << STATIC) | (1L << READONLY) | (1L << SEALED) | (1L << IDENTIFIER))) != 0)) {
				{
				{
				State = 177;
				classMember();
				}
				}
				State = 182;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 183;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StructDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRUCT() { return GetToken(MarlinParser.STRUCT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(MarlinParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(MarlinParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(MarlinParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ModifierContext[] modifier() {
			return GetRuleContexts<ModifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ModifierContext modifier(int i) {
			return GetRuleContext<ModifierContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StructMemberContext[] structMember() {
			return GetRuleContexts<StructMemberContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StructMemberContext structMember(int i) {
			return GetRuleContext<StructMemberContext>(i);
		}
		public StructDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_structDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStructDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StructDeclarationContext structDeclaration() {
		StructDeclarationContext _localctx = new StructDeclarationContext(Context, State);
		EnterRule(_localctx, 22, RULE_structDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 188;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PRIVATE) | (1L << INTERNAL) | (1L << PUBLIC) | (1L << STATIC) | (1L << READONLY) | (1L << SEALED))) != 0)) {
				{
				{
				State = 185;
				modifier();
				}
				}
				State = 190;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 191;
			Match(STRUCT);
			State = 192;
			Match(IDENTIFIER);
			State = 193;
			Match(LBRACE);
			State = 197;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PRIVATE) | (1L << INTERNAL) | (1L << PUBLIC) | (1L << STATIC) | (1L << READONLY) | (1L << SEALED) | (1L << IDENTIFIER))) != 0)) {
				{
				{
				State = 194;
				structMember();
				}
				}
				State = 199;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 200;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MethodDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(MarlinParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public MethodBodyContext methodBody() {
			return GetRuleContext<MethodBodyContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ModifierContext[] modifier() {
			return GetRuleContexts<ModifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ModifierContext modifier(int i) {
			return GetRuleContext<ModifierContext>(i);
		}
		public MethodDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_methodDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMethodDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MethodDeclarationContext methodDeclaration() {
		MethodDeclarationContext _localctx = new MethodDeclarationContext(Context, State);
		EnterRule(_localctx, 24, RULE_methodDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 205;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PRIVATE) | (1L << INTERNAL) | (1L << PUBLIC) | (1L << STATIC) | (1L << READONLY) | (1L << SEALED))) != 0)) {
				{
				{
				State = 202;
				modifier();
				}
				}
				State = 207;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 208;
			typeName(0);
			State = 209;
			Match(IDENTIFIER);
			State = 210;
			methodBody();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MethodCallContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public MemberAccessContext memberAccess() {
			return GetRuleContext<MemberAccessContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public GiveArgsContext giveArgs() {
			return GetRuleContext<GiveArgsContext>(0);
		}
		public MethodCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_methodCall; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMethodCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MethodCallContext methodCall() {
		MethodCallContext _localctx = new MethodCallContext(Context, State);
		EnterRule(_localctx, 26, RULE_methodCall);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 212;
			memberAccess(0);
			State = 213;
			giveArgs();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(MarlinParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ModifierContext[] modifier() {
			return GetRuleContexts<ModifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ModifierContext modifier(int i) {
			return GetRuleContext<ModifierContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NATIVE() { return GetToken(MarlinParser.NATIVE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(MarlinParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public VariableDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableDeclarationContext variableDeclaration() {
		VariableDeclarationContext _localctx = new VariableDeclarationContext(Context, State);
		EnterRule(_localctx, 28, RULE_variableDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 218;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PRIVATE) | (1L << INTERNAL) | (1L << PUBLIC) | (1L << STATIC) | (1L << READONLY) | (1L << SEALED))) != 0)) {
				{
				{
				State = 215;
				modifier();
				}
				}
				State = 220;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 221;
			typeName(0);
			State = 223;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==NATIVE) {
				{
				State = 222;
				Match(NATIVE);
				}
			}

			State = 225;
			Match(IDENTIFIER);
			State = 228;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ASSIGN) {
				{
				State = 226;
				Match(ASSIGN);
				State = 227;
				expression();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LocalVariableDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(MarlinParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(MarlinParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public LocalVariableDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_localVariableDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLocalVariableDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LocalVariableDeclarationContext localVariableDeclaration() {
		LocalVariableDeclarationContext _localctx = new LocalVariableDeclarationContext(Context, State);
		EnterRule(_localctx, 30, RULE_localVariableDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 230;
			typeName(0);
			State = 231;
			Match(IDENTIFIER);
			State = 234;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ASSIGN) {
				{
				State = 232;
				Match(ASSIGN);
				State = 233;
				expression();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableAssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public MemberAccessContext memberAccess() {
			return GetRuleContext<MemberAccessContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(MarlinParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public VariableAssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableAssignment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableAssignmentContext variableAssignment() {
		VariableAssignmentContext _localctx = new VariableAssignmentContext(Context, State);
		EnterRule(_localctx, 32, RULE_variableAssignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 236;
			memberAccess(0);
			State = 237;
			Match(ASSIGN);
			State = 238;
			expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MemberAccessContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(MarlinParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT() { return GetToken(MarlinParser.DOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACKET() { return GetToken(MarlinParser.LBRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACKET() { return GetToken(MarlinParser.RBRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public MemberAccessContext[] memberAccess() {
			return GetRuleContexts<MemberAccessContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemberAccessContext memberAccess(int i) {
			return GetRuleContext<MemberAccessContext>(i);
		}
		public MemberAccessContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_memberAccess; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMemberAccess(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MemberAccessContext memberAccess() {
		return memberAccess(0);
	}

	private MemberAccessContext memberAccess(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		MemberAccessContext _localctx = new MemberAccessContext(Context, _parentState);
		MemberAccessContext _prevctx = _localctx;
		int _startState = 34;
		EnterRecursionRule(_localctx, 34, RULE_memberAccess, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 260;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,25,Context) ) {
			case 1:
				{
				State = 244;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,22,Context) ) {
				case 1:
					{
					State = 241;
					typeName(0);
					State = 242;
					Match(DOT);
					}
					break;
				}
				State = 246;
				Match(IDENTIFIER);
				State = 251;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,23,Context) ) {
				case 1:
					{
					State = 247;
					Match(LBRACKET);
					State = 248;
					expression();
					State = 249;
					Match(RBRACKET);
					}
					break;
				}
				}
				break;
			case 2:
				{
				State = 253;
				Match(IDENTIFIER);
				State = 258;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,24,Context) ) {
				case 1:
					{
					State = 254;
					Match(LBRACKET);
					State = 255;
					expression();
					State = 256;
					Match(RBRACKET);
					}
					break;
				}
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 267;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,26,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new MemberAccessContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_memberAccess);
					State = 262;
					if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
					State = 263;
					Match(DOT);
					State = 264;
					memberAccess(3);
					}
					} 
				}
				State = 269;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,26,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ArrayInitializerContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEW() { return GetToken(MarlinParser.NEW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACKET() { return GetToken(MarlinParser.LBRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] RBRACKET() { return GetTokens(MarlinParser.RBRACKET); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACKET(int i) {
			return GetToken(MarlinParser.RBRACKET, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(MarlinParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(MarlinParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(MarlinParser.COMMA, i);
		}
		public ArrayInitializerContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arrayInitializer; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrayInitializer(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArrayInitializerContext arrayInitializer() {
		ArrayInitializerContext _localctx = new ArrayInitializerContext(Context, State);
		EnterRule(_localctx, 36, RULE_arrayInitializer);
		int _la;
		try {
			State = 291;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,28,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 270;
				Match(NEW);
				State = 271;
				typeName(0);
				State = 272;
				Match(LBRACKET);
				State = 273;
				expression();
				State = 274;
				Match(RBRACKET);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 276;
				Match(NEW);
				State = 277;
				typeName(0);
				State = 278;
				Match(LBRACKET);
				State = 279;
				Match(RBRACKET);
				State = 280;
				Match(LBRACE);
				State = 281;
				expression();
				State = 286;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 282;
					Match(COMMA);
					State = 283;
					expression();
					}
					}
					State = 288;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 289;
				Match(RBRACKET);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NativeCallContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AT() { return GetToken(MarlinParser.AT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACKET() { return GetToken(MarlinParser.LBRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public GiveArgsContext giveArgs() {
			return GetRuleContext<GiveArgsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACKET() { return GetToken(MarlinParser.RBRACKET, 0); }
		public NativeCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nativeCall; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNativeCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NativeCallContext nativeCall() {
		NativeCallContext _localctx = new NativeCallContext(Context, State);
		EnterRule(_localctx, 38, RULE_nativeCall);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 293;
			Match(AT);
			State = 294;
			Match(LBRACKET);
			State = 295;
			giveArgs();
			State = 296;
			Match(RBRACKET);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReturnContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RETURN() { return GetToken(MarlinParser.RETURN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ReturnContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_return; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReturn(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ReturnContext @return() {
		ReturnContext _localctx = new ReturnContext(Context, State);
		EnterRule(_localctx, 40, RULE_return);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 298;
			Match(RETURN);
			State = 300;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << NEW) | (1L << NULL) | (1L << TRUE) | (1L << FALSE) | (1L << AT) | (1L << LPAREN) | (1L << IDENTIFIER) | (1L << INTEGER) | (1L << NORMAL_STRING) | (1L << CHARACTER) | (1L << DOUBLE))) != 0)) {
				{
				State = 299;
				expression();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClassMemberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VariableDeclarationContext variableDeclaration() {
			return GetRuleContext<VariableDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(MarlinParser.SEMICOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public MethodDeclarationContext methodDeclaration() {
			return GetRuleContext<MethodDeclarationContext>(0);
		}
		public ClassMemberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_classMember; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClassMember(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ClassMemberContext classMember() {
		ClassMemberContext _localctx = new ClassMemberContext(Context, State);
		EnterRule(_localctx, 42, RULE_classMember);
		try {
			State = 306;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,30,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 302;
				variableDeclaration();
				State = 303;
				Match(SEMICOLON);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 305;
				methodDeclaration();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StructMemberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VariableDeclarationContext variableDeclaration() {
			return GetRuleContext<VariableDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(MarlinParser.SEMICOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public MethodDeclarationContext methodDeclaration() {
			return GetRuleContext<MethodDeclarationContext>(0);
		}
		public StructMemberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_structMember; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStructMember(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StructMemberContext structMember() {
		StructMemberContext _localctx = new StructMemberContext(Context, State);
		EnterRule(_localctx, 44, RULE_structMember);
		try {
			State = 312;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,31,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 308;
				variableDeclaration();
				State = 309;
				Match(SEMICOLON);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 311;
				methodDeclaration();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MethodBodyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpectArgsContext expectArgs() {
			return GetRuleContext<ExpectArgsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ARROW() { return GetToken(MarlinParser.ARROW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(MarlinParser.SEMICOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(MarlinParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(MarlinParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public MethodBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_methodBody; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMethodBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MethodBodyContext methodBody() {
		MethodBodyContext _localctx = new MethodBodyContext(Context, State);
		EnterRule(_localctx, 46, RULE_methodBody);
		int _la;
		try {
			State = 329;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,33,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 314;
				expectArgs();
				State = 315;
				Match(ARROW);
				State = 316;
				expression();
				State = 317;
				Match(SEMICOLON);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 319;
				expectArgs();
				State = 320;
				Match(LBRACE);
				State = 324;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << RETURN) | (1L << AT) | (1L << IDENTIFIER))) != 0)) {
					{
					{
					State = 321;
					statement();
					}
					}
					State = 326;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 327;
				Match(RBRACE);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BooleanLiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRUE() { return GetToken(MarlinParser.TRUE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FALSE() { return GetToken(MarlinParser.FALSE, 0); }
		public BooleanLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_booleanLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBooleanLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BooleanLiteralContext booleanLiteral() {
		BooleanLiteralContext _localctx = new BooleanLiteralContext(Context, State);
		EnterRule(_localctx, 48, RULE_booleanLiteral);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 331;
			_la = TokenStream.LA(1);
			if ( !(_la==TRUE || _la==FALSE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringLiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NORMAL_STRING() { return GetToken(MarlinParser.NORMAL_STRING, 0); }
		public StringLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stringLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStringLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StringLiteralContext stringLiteral() {
		StringLiteralContext _localctx = new StringLiteralContext(Context, State);
		EnterRule(_localctx, 50, RULE_stringLiteral);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 333;
			Match(NORMAL_STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CharacterLiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CHARACTER() { return GetToken(MarlinParser.CHARACTER, 0); }
		public CharacterLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_characterLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCharacterLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CharacterLiteralContext characterLiteral() {
		CharacterLiteralContext _localctx = new CharacterLiteralContext(Context, State);
		EnterRule(_localctx, 52, RULE_characterLiteral);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 335;
			Match(CHARACTER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberLiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTEGER() { return GetToken(MarlinParser.INTEGER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE() { return GetToken(MarlinParser.DOUBLE, 0); }
		public NumberLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numberLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberLiteralContext numberLiteral() {
		NumberLiteralContext _localctx = new NumberLiteralContext(Context, State);
		EnterRule(_localctx, 54, RULE_numberLiteral);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 337;
			_la = TokenStream.LA(1);
			if ( !(_la==INTEGER || _la==DOUBLE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NullLiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NULL() { return GetToken(MarlinParser.NULL, 0); }
		public NullLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nullLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNullLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NullLiteralContext nullLiteral() {
		NullLiteralContext _localctx = new NullLiteralContext(Context, State);
		EnterRule(_localctx, 56, RULE_nullLiteral);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 339;
			Match(NULL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 1: return typeName_sempred((TypeNameContext)_localctx, predIndex);
		case 17: return memberAccess_sempred((MemberAccessContext)_localctx, predIndex);
		}
		return true;
	}
	private bool typeName_sempred(TypeNameContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 2);
		}
		return true;
	}
	private bool memberAccess_sempred(MemberAccessContext _localctx, int predIndex) {
		switch (predIndex) {
		case 1: return Precpred(Context, 2);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '\'', '\x158', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x4', '\x1C', '\t', '\x1C', '\x4', '\x1D', '\t', 
		'\x1D', '\x4', '\x1E', '\t', '\x1E', '\x3', '\x2', '\x3', '\x2', '\a', 
		'\x2', '?', '\n', '\x2', '\f', '\x2', '\xE', '\x2', '\x42', '\v', '\x2', 
		'\x5', '\x2', '\x44', '\n', '\x2', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', 'L', '\n', 
		'\x3', '\f', '\x3', '\xE', '\x3', 'O', '\v', '\x3', '\x3', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\a', '\x3', 'T', '\n', '\x3', '\f', '\x3', '\xE', 
		'\x3', 'W', '\v', '\x3', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', 
		'\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\a', '\x6', '\x63', '\n', '\x6', '\f', '\x6', '\xE', 
		'\x6', '\x66', '\v', '\x6', '\x5', '\x6', 'h', '\n', '\x6', '\x3', '\x6', 
		'\x3', '\x6', '\x3', '\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', 
		'\b', '\x3', '\b', '\x3', '\b', '\a', '\b', 's', '\n', '\b', '\f', '\b', 
		'\xE', '\b', 'v', '\v', '\b', '\x5', '\b', 'x', '\n', '\b', '\x3', '\b', 
		'\x3', '\b', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x5', 
		'\t', '\x8B', '\n', '\t', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x5', '\n', '\x9A', 
		'\n', '\n', '\x3', '\v', '\x3', '\v', '\x5', '\v', '\x9E', '\n', '\v', 
		'\x3', '\f', '\a', '\f', '\xA1', '\n', '\f', '\f', '\f', '\xE', '\f', 
		'\xA4', '\v', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\a', '\f', '\xAC', '\n', '\f', '\f', '\f', 
		'\xE', '\f', '\xAF', '\v', '\f', '\x5', '\f', '\xB1', '\n', '\f', '\x3', 
		'\f', '\x3', '\f', '\a', '\f', '\xB5', '\n', '\f', '\f', '\f', '\xE', 
		'\f', '\xB8', '\v', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\r', '\a', 
		'\r', '\xBD', '\n', '\r', '\f', '\r', '\xE', '\r', '\xC0', '\v', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\r', '\a', '\r', '\xC6', 
		'\n', '\r', '\f', '\r', '\xE', '\r', '\xC9', '\v', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\xE', '\a', '\xE', '\xCE', '\n', '\xE', '\f', '\xE', 
		'\xE', '\xE', '\xD1', '\v', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x3', '\xF', '\x3', 
		'\x10', '\a', '\x10', '\xDB', '\n', '\x10', '\f', '\x10', '\xE', '\x10', 
		'\xDE', '\v', '\x10', '\x3', '\x10', '\x3', '\x10', '\x5', '\x10', '\xE2', 
		'\n', '\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x5', '\x10', 
		'\xE7', '\n', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', 
		'\x11', '\x5', '\x11', '\xED', '\n', '\x11', '\x3', '\x12', '\x3', '\x12', 
		'\x3', '\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x13', '\x5', '\x13', '\xF7', '\n', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x5', '\x13', '\xFE', 
		'\n', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x13', '\x5', '\x13', '\x105', '\n', '\x13', '\x5', '\x13', '\x107', 
		'\n', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\a', '\x13', 
		'\x10C', '\n', '\x13', '\f', '\x13', '\xE', '\x13', '\x10F', '\v', '\x13', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\a', '\x14', 
		'\x11F', '\n', '\x14', '\f', '\x14', '\xE', '\x14', '\x122', '\v', '\x14', 
		'\x3', '\x14', '\x3', '\x14', '\x5', '\x14', '\x126', '\n', '\x14', '\x3', 
		'\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', '\x15', '\x3', 
		'\x16', '\x3', '\x16', '\x5', '\x16', '\x12F', '\n', '\x16', '\x3', '\x17', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x5', '\x17', '\x135', '\n', 
		'\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x5', 
		'\x18', '\x13B', '\n', '\x18', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', '\x3', '\x19', 
		'\a', '\x19', '\x145', '\n', '\x19', '\f', '\x19', '\xE', '\x19', '\x148', 
		'\v', '\x19', '\x3', '\x19', '\x3', '\x19', '\x5', '\x19', '\x14C', '\n', 
		'\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', '\x3', '\x1B', '\x3', 
		'\x1C', '\x3', '\x1C', '\x3', '\x1D', '\x3', '\x1D', '\x3', '\x1E', '\x3', 
		'\x1E', '\x3', '\x1E', '\x2', '\x4', '\x4', '$', '\x1F', '\x2', '\x4', 
		'\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', '\x18', 
		'\x1A', '\x1C', '\x1E', ' ', '\"', '$', '&', '(', '*', ',', '.', '\x30', 
		'\x32', '\x34', '\x36', '\x38', ':', '\x2', '\x5', '\x3', '\x2', '\r', 
		'\x12', '\x3', '\x2', '\v', '\f', '\x4', '\x2', '$', '$', '\'', '\'', 
		'\x2', '\x167', '\x2', '\x43', '\x3', '\x2', '\x2', '\x2', '\x4', 'G', 
		'\x3', '\x2', '\x2', '\x2', '\x6', 'X', '\x3', '\x2', '\x2', '\x2', '\b', 
		'\\', '\x3', '\x2', '\x2', '\x2', '\n', '^', '\x3', '\x2', '\x2', '\x2', 
		'\f', 'k', '\x3', '\x2', '\x2', '\x2', '\xE', 'n', '\x3', '\x2', '\x2', 
		'\x2', '\x10', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x12', '\x99', '\x3', 
		'\x2', '\x2', '\x2', '\x14', '\x9D', '\x3', '\x2', '\x2', '\x2', '\x16', 
		'\xA2', '\x3', '\x2', '\x2', '\x2', '\x18', '\xBE', '\x3', '\x2', '\x2', 
		'\x2', '\x1A', '\xCF', '\x3', '\x2', '\x2', '\x2', '\x1C', '\xD6', '\x3', 
		'\x2', '\x2', '\x2', '\x1E', '\xDC', '\x3', '\x2', '\x2', '\x2', ' ', 
		'\xE8', '\x3', '\x2', '\x2', '\x2', '\"', '\xEE', '\x3', '\x2', '\x2', 
		'\x2', '$', '\x106', '\x3', '\x2', '\x2', '\x2', '&', '\x125', '\x3', 
		'\x2', '\x2', '\x2', '(', '\x127', '\x3', '\x2', '\x2', '\x2', '*', '\x12C', 
		'\x3', '\x2', '\x2', '\x2', ',', '\x134', '\x3', '\x2', '\x2', '\x2', 
		'.', '\x13A', '\x3', '\x2', '\x2', '\x2', '\x30', '\x14B', '\x3', '\x2', 
		'\x2', '\x2', '\x32', '\x14D', '\x3', '\x2', '\x2', '\x2', '\x34', '\x14F', 
		'\x3', '\x2', '\x2', '\x2', '\x36', '\x151', '\x3', '\x2', '\x2', '\x2', 
		'\x38', '\x153', '\x3', '\x2', '\x2', '\x2', ':', '\x155', '\x3', '\x2', 
		'\x2', '\x2', '<', '@', '\x5', '\x6', '\x4', '\x2', '=', '?', '\x5', '\x14', 
		'\v', '\x2', '>', '=', '\x3', '\x2', '\x2', '\x2', '?', '\x42', '\x3', 
		'\x2', '\x2', '\x2', '@', '>', '\x3', '\x2', '\x2', '\x2', '@', '\x41', 
		'\x3', '\x2', '\x2', '\x2', '\x41', '\x44', '\x3', '\x2', '\x2', '\x2', 
		'\x42', '@', '\x3', '\x2', '\x2', '\x2', '\x43', '<', '\x3', '\x2', '\x2', 
		'\x2', '\x43', '\x44', '\x3', '\x2', '\x2', '\x2', '\x44', '\x45', '\x3', 
		'\x2', '\x2', '\x2', '\x45', '\x46', '\a', '\x2', '\x2', '\x3', '\x46', 
		'\x3', '\x3', '\x2', '\x2', '\x2', 'G', 'H', '\b', '\x3', '\x1', '\x2', 
		'H', 'M', '\a', '#', '\x2', '\x2', 'I', 'J', '\a', '!', '\x2', '\x2', 
		'J', 'L', '\a', '#', '\x2', '\x2', 'K', 'I', '\x3', '\x2', '\x2', '\x2', 
		'L', 'O', '\x3', '\x2', '\x2', '\x2', 'M', 'K', '\x3', '\x2', '\x2', '\x2', 
		'M', 'N', '\x3', '\x2', '\x2', '\x2', 'N', 'U', '\x3', '\x2', '\x2', '\x2', 
		'O', 'M', '\x3', '\x2', '\x2', '\x2', 'P', 'Q', '\f', '\x4', '\x2', '\x2', 
		'Q', 'R', '\a', '\x1C', '\x2', '\x2', 'R', 'T', '\a', '\x1D', '\x2', '\x2', 
		'S', 'P', '\x3', '\x2', '\x2', '\x2', 'T', 'W', '\x3', '\x2', '\x2', '\x2', 
		'U', 'S', '\x3', '\x2', '\x2', '\x2', 'U', 'V', '\x3', '\x2', '\x2', '\x2', 
		'V', '\x5', '\x3', '\x2', '\x2', '\x2', 'W', 'U', '\x3', '\x2', '\x2', 
		'\x2', 'X', 'Y', '\a', '\x4', '\x2', '\x2', 'Y', 'Z', '\x5', '\x4', '\x3', 
		'\x2', 'Z', '[', '\a', '\x17', '\x2', '\x2', '[', '\a', '\x3', '\x2', 
		'\x2', '\x2', '\\', ']', '\t', '\x2', '\x2', '\x2', ']', '\t', '\x3', 
		'\x2', '\x2', '\x2', '^', 'g', '\a', '\x1A', '\x2', '\x2', '_', '\x64', 
		'\x5', '\f', '\a', '\x2', '`', '\x61', '\a', '\x15', '\x2', '\x2', '\x61', 
		'\x63', '\x5', '\f', '\a', '\x2', '\x62', '`', '\x3', '\x2', '\x2', '\x2', 
		'\x63', '\x66', '\x3', '\x2', '\x2', '\x2', '\x64', '\x62', '\x3', '\x2', 
		'\x2', '\x2', '\x64', '\x65', '\x3', '\x2', '\x2', '\x2', '\x65', 'h', 
		'\x3', '\x2', '\x2', '\x2', '\x66', '\x64', '\x3', '\x2', '\x2', '\x2', 
		'g', '_', '\x3', '\x2', '\x2', '\x2', 'g', 'h', '\x3', '\x2', '\x2', '\x2', 
		'h', 'i', '\x3', '\x2', '\x2', '\x2', 'i', 'j', '\a', '\x1B', '\x2', '\x2', 
		'j', '\v', '\x3', '\x2', '\x2', '\x2', 'k', 'l', '\x5', '\x4', '\x3', 
		'\x2', 'l', 'm', '\a', '#', '\x2', '\x2', 'm', '\r', '\x3', '\x2', '\x2', 
		'\x2', 'n', 'w', '\a', '\x1A', '\x2', '\x2', 'o', 't', '\x5', '\x12', 
		'\n', '\x2', 'p', 'q', '\a', '\x15', '\x2', '\x2', 'q', 's', '\x5', '\x12', 
		'\n', '\x2', 'r', 'p', '\x3', '\x2', '\x2', '\x2', 's', 'v', '\x3', '\x2', 
		'\x2', '\x2', 't', 'r', '\x3', '\x2', '\x2', '\x2', 't', 'u', '\x3', '\x2', 
		'\x2', '\x2', 'u', 'x', '\x3', '\x2', '\x2', '\x2', 'v', 't', '\x3', '\x2', 
		'\x2', '\x2', 'w', 'o', '\x3', '\x2', '\x2', '\x2', 'w', 'x', '\x3', '\x2', 
		'\x2', '\x2', 'x', 'y', '\x3', '\x2', '\x2', '\x2', 'y', 'z', '\a', '\x1B', 
		'\x2', '\x2', 'z', '\xF', '\x3', '\x2', '\x2', '\x2', '{', '|', '\x5', 
		'\x1C', '\xF', '\x2', '|', '}', '\a', '\x17', '\x2', '\x2', '}', '\x8B', 
		'\x3', '\x2', '\x2', '\x2', '~', '\x7F', '\x5', ' ', '\x11', '\x2', '\x7F', 
		'\x80', '\a', '\x17', '\x2', '\x2', '\x80', '\x8B', '\x3', '\x2', '\x2', 
		'\x2', '\x81', '\x82', '\x5', '\"', '\x12', '\x2', '\x82', '\x83', '\a', 
		'\x17', '\x2', '\x2', '\x83', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x84', 
		'\x85', '\x5', '*', '\x16', '\x2', '\x85', '\x86', '\a', '\x17', '\x2', 
		'\x2', '\x86', '\x8B', '\x3', '\x2', '\x2', '\x2', '\x87', '\x88', '\x5', 
		'(', '\x15', '\x2', '\x88', '\x89', '\a', '\x17', '\x2', '\x2', '\x89', 
		'\x8B', '\x3', '\x2', '\x2', '\x2', '\x8A', '{', '\x3', '\x2', '\x2', 
		'\x2', '\x8A', '~', '\x3', '\x2', '\x2', '\x2', '\x8A', '\x81', '\x3', 
		'\x2', '\x2', '\x2', '\x8A', '\x84', '\x3', '\x2', '\x2', '\x2', '\x8A', 
		'\x87', '\x3', '\x2', '\x2', '\x2', '\x8B', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x8C', '\x8D', '\a', '\x1A', '\x2', '\x2', '\x8D', '\x8E', '\x5', 
		'\x12', '\n', '\x2', '\x8E', '\x8F', '\a', '\x1B', '\x2', '\x2', '\x8F', 
		'\x9A', '\x3', '\x2', '\x2', '\x2', '\x90', '\x9A', '\x5', '\x1C', '\xF', 
		'\x2', '\x91', '\x9A', '\x5', '$', '\x13', '\x2', '\x92', '\x9A', '\x5', 
		':', '\x1E', '\x2', '\x93', '\x9A', '\x5', '\x32', '\x1A', '\x2', '\x94', 
		'\x9A', '\x5', '\x34', '\x1B', '\x2', '\x95', '\x9A', '\x5', '\x36', '\x1C', 
		'\x2', '\x96', '\x9A', '\x5', '\x38', '\x1D', '\x2', '\x97', '\x9A', '\x5', 
		'&', '\x14', '\x2', '\x98', '\x9A', '\x5', '(', '\x15', '\x2', '\x99', 
		'\x8C', '\x3', '\x2', '\x2', '\x2', '\x99', '\x90', '\x3', '\x2', '\x2', 
		'\x2', '\x99', '\x91', '\x3', '\x2', '\x2', '\x2', '\x99', '\x92', '\x3', 
		'\x2', '\x2', '\x2', '\x99', '\x93', '\x3', '\x2', '\x2', '\x2', '\x99', 
		'\x94', '\x3', '\x2', '\x2', '\x2', '\x99', '\x95', '\x3', '\x2', '\x2', 
		'\x2', '\x99', '\x96', '\x3', '\x2', '\x2', '\x2', '\x99', '\x97', '\x3', 
		'\x2', '\x2', '\x2', '\x99', '\x98', '\x3', '\x2', '\x2', '\x2', '\x9A', 
		'\x13', '\x3', '\x2', '\x2', '\x2', '\x9B', '\x9E', '\x5', '\x16', '\f', 
		'\x2', '\x9C', '\x9E', '\x5', '\x18', '\r', '\x2', '\x9D', '\x9B', '\x3', 
		'\x2', '\x2', '\x2', '\x9D', '\x9C', '\x3', '\x2', '\x2', '\x2', '\x9E', 
		'\x15', '\x3', '\x2', '\x2', '\x2', '\x9F', '\xA1', '\x5', '\b', '\x5', 
		'\x2', '\xA0', '\x9F', '\x3', '\x2', '\x2', '\x2', '\xA1', '\xA4', '\x3', 
		'\x2', '\x2', '\x2', '\xA2', '\xA0', '\x3', '\x2', '\x2', '\x2', '\xA2', 
		'\xA3', '\x3', '\x2', '\x2', '\x2', '\xA3', '\xA5', '\x3', '\x2', '\x2', 
		'\x2', '\xA4', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA5', '\xA6', '\a', 
		'\x5', '\x2', '\x2', '\xA6', '\xB0', '\a', '#', '\x2', '\x2', '\xA7', 
		'\xA8', '\a', '\x16', '\x2', '\x2', '\xA8', '\xAD', '\x5', '\x4', '\x3', 
		'\x2', '\xA9', '\xAA', '\a', '\x15', '\x2', '\x2', '\xAA', '\xAC', '\x5', 
		'\x4', '\x3', '\x2', '\xAB', '\xA9', '\x3', '\x2', '\x2', '\x2', '\xAC', 
		'\xAF', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAB', '\x3', '\x2', '\x2', 
		'\x2', '\xAD', '\xAE', '\x3', '\x2', '\x2', '\x2', '\xAE', '\xB1', '\x3', 
		'\x2', '\x2', '\x2', '\xAF', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xB0', 
		'\xA7', '\x3', '\x2', '\x2', '\x2', '\xB0', '\xB1', '\x3', '\x2', '\x2', 
		'\x2', '\xB1', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB2', '\xB6', '\a', 
		'\x18', '\x2', '\x2', '\xB3', '\xB5', '\x5', ',', '\x17', '\x2', '\xB4', 
		'\xB3', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB8', '\x3', '\x2', '\x2', 
		'\x2', '\xB6', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB6', '\xB7', '\x3', 
		'\x2', '\x2', '\x2', '\xB7', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xB8', 
		'\xB6', '\x3', '\x2', '\x2', '\x2', '\xB9', '\xBA', '\a', '\x19', '\x2', 
		'\x2', '\xBA', '\x17', '\x3', '\x2', '\x2', '\x2', '\xBB', '\xBD', '\x5', 
		'\b', '\x5', '\x2', '\xBC', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xBD', 
		'\xC0', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBC', '\x3', '\x2', '\x2', 
		'\x2', '\xBE', '\xBF', '\x3', '\x2', '\x2', '\x2', '\xBF', '\xC1', '\x3', 
		'\x2', '\x2', '\x2', '\xC0', '\xBE', '\x3', '\x2', '\x2', '\x2', '\xC1', 
		'\xC2', '\a', '\x6', '\x2', '\x2', '\xC2', '\xC3', '\a', '#', '\x2', '\x2', 
		'\xC3', '\xC7', '\a', '\x18', '\x2', '\x2', '\xC4', '\xC6', '\x5', '.', 
		'\x18', '\x2', '\xC5', '\xC4', '\x3', '\x2', '\x2', '\x2', '\xC6', '\xC9', 
		'\x3', '\x2', '\x2', '\x2', '\xC7', '\xC5', '\x3', '\x2', '\x2', '\x2', 
		'\xC7', '\xC8', '\x3', '\x2', '\x2', '\x2', '\xC8', '\xCA', '\x3', '\x2', 
		'\x2', '\x2', '\xC9', '\xC7', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', 
		'\a', '\x19', '\x2', '\x2', '\xCB', '\x19', '\x3', '\x2', '\x2', '\x2', 
		'\xCC', '\xCE', '\x5', '\b', '\x5', '\x2', '\xCD', '\xCC', '\x3', '\x2', 
		'\x2', '\x2', '\xCE', '\xD1', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xCD', 
		'\x3', '\x2', '\x2', '\x2', '\xCF', '\xD0', '\x3', '\x2', '\x2', '\x2', 
		'\xD0', '\xD2', '\x3', '\x2', '\x2', '\x2', '\xD1', '\xCF', '\x3', '\x2', 
		'\x2', '\x2', '\xD2', '\xD3', '\x5', '\x4', '\x3', '\x2', '\xD3', '\xD4', 
		'\a', '#', '\x2', '\x2', '\xD4', '\xD5', '\x5', '\x30', '\x19', '\x2', 
		'\xD5', '\x1B', '\x3', '\x2', '\x2', '\x2', '\xD6', '\xD7', '\x5', '$', 
		'\x13', '\x2', '\xD7', '\xD8', '\x5', '\xE', '\b', '\x2', '\xD8', '\x1D', 
		'\x3', '\x2', '\x2', '\x2', '\xD9', '\xDB', '\x5', '\b', '\x5', '\x2', 
		'\xDA', '\xD9', '\x3', '\x2', '\x2', '\x2', '\xDB', '\xDE', '\x3', '\x2', 
		'\x2', '\x2', '\xDC', '\xDA', '\x3', '\x2', '\x2', '\x2', '\xDC', '\xDD', 
		'\x3', '\x2', '\x2', '\x2', '\xDD', '\xDF', '\x3', '\x2', '\x2', '\x2', 
		'\xDE', '\xDC', '\x3', '\x2', '\x2', '\x2', '\xDF', '\xE1', '\x5', '\x4', 
		'\x3', '\x2', '\xE0', '\xE2', '\a', '\t', '\x2', '\x2', '\xE1', '\xE0', 
		'\x3', '\x2', '\x2', '\x2', '\xE1', '\xE2', '\x3', '\x2', '\x2', '\x2', 
		'\xE2', '\xE3', '\x3', '\x2', '\x2', '\x2', '\xE3', '\xE6', '\a', '#', 
		'\x2', '\x2', '\xE4', '\xE5', '\a', '\x1E', '\x2', '\x2', '\xE5', '\xE7', 
		'\x5', '\x12', '\n', '\x2', '\xE6', '\xE4', '\x3', '\x2', '\x2', '\x2', 
		'\xE6', '\xE7', '\x3', '\x2', '\x2', '\x2', '\xE7', '\x1F', '\x3', '\x2', 
		'\x2', '\x2', '\xE8', '\xE9', '\x5', '\x4', '\x3', '\x2', '\xE9', '\xEC', 
		'\a', '#', '\x2', '\x2', '\xEA', '\xEB', '\a', '\x1E', '\x2', '\x2', '\xEB', 
		'\xED', '\x5', '\x12', '\n', '\x2', '\xEC', '\xEA', '\x3', '\x2', '\x2', 
		'\x2', '\xEC', '\xED', '\x3', '\x2', '\x2', '\x2', '\xED', '!', '\x3', 
		'\x2', '\x2', '\x2', '\xEE', '\xEF', '\x5', '$', '\x13', '\x2', '\xEF', 
		'\xF0', '\a', '\x1E', '\x2', '\x2', '\xF0', '\xF1', '\x5', '\x12', '\n', 
		'\x2', '\xF1', '#', '\x3', '\x2', '\x2', '\x2', '\xF2', '\xF6', '\b', 
		'\x13', '\x1', '\x2', '\xF3', '\xF4', '\x5', '\x4', '\x3', '\x2', '\xF4', 
		'\xF5', '\a', '\x14', '\x2', '\x2', '\xF5', '\xF7', '\x3', '\x2', '\x2', 
		'\x2', '\xF6', '\xF3', '\x3', '\x2', '\x2', '\x2', '\xF6', '\xF7', '\x3', 
		'\x2', '\x2', '\x2', '\xF7', '\xF8', '\x3', '\x2', '\x2', '\x2', '\xF8', 
		'\xFD', '\a', '#', '\x2', '\x2', '\xF9', '\xFA', '\a', '\x1C', '\x2', 
		'\x2', '\xFA', '\xFB', '\x5', '\x12', '\n', '\x2', '\xFB', '\xFC', '\a', 
		'\x1D', '\x2', '\x2', '\xFC', '\xFE', '\x3', '\x2', '\x2', '\x2', '\xFD', 
		'\xF9', '\x3', '\x2', '\x2', '\x2', '\xFD', '\xFE', '\x3', '\x2', '\x2', 
		'\x2', '\xFE', '\x107', '\x3', '\x2', '\x2', '\x2', '\xFF', '\x104', '\a', 
		'#', '\x2', '\x2', '\x100', '\x101', '\a', '\x1C', '\x2', '\x2', '\x101', 
		'\x102', '\x5', '\x12', '\n', '\x2', '\x102', '\x103', '\a', '\x1D', '\x2', 
		'\x2', '\x103', '\x105', '\x3', '\x2', '\x2', '\x2', '\x104', '\x100', 
		'\x3', '\x2', '\x2', '\x2', '\x104', '\x105', '\x3', '\x2', '\x2', '\x2', 
		'\x105', '\x107', '\x3', '\x2', '\x2', '\x2', '\x106', '\xF2', '\x3', 
		'\x2', '\x2', '\x2', '\x106', '\xFF', '\x3', '\x2', '\x2', '\x2', '\x107', 
		'\x10D', '\x3', '\x2', '\x2', '\x2', '\x108', '\x109', '\f', '\x4', '\x2', 
		'\x2', '\x109', '\x10A', '\a', '\x14', '\x2', '\x2', '\x10A', '\x10C', 
		'\x5', '$', '\x13', '\x5', '\x10B', '\x108', '\x3', '\x2', '\x2', '\x2', 
		'\x10C', '\x10F', '\x3', '\x2', '\x2', '\x2', '\x10D', '\x10B', '\x3', 
		'\x2', '\x2', '\x2', '\x10D', '\x10E', '\x3', '\x2', '\x2', '\x2', '\x10E', 
		'%', '\x3', '\x2', '\x2', '\x2', '\x10F', '\x10D', '\x3', '\x2', '\x2', 
		'\x2', '\x110', '\x111', '\a', '\b', '\x2', '\x2', '\x111', '\x112', '\x5', 
		'\x4', '\x3', '\x2', '\x112', '\x113', '\a', '\x1C', '\x2', '\x2', '\x113', 
		'\x114', '\x5', '\x12', '\n', '\x2', '\x114', '\x115', '\a', '\x1D', '\x2', 
		'\x2', '\x115', '\x126', '\x3', '\x2', '\x2', '\x2', '\x116', '\x117', 
		'\a', '\b', '\x2', '\x2', '\x117', '\x118', '\x5', '\x4', '\x3', '\x2', 
		'\x118', '\x119', '\a', '\x1C', '\x2', '\x2', '\x119', '\x11A', '\a', 
		'\x1D', '\x2', '\x2', '\x11A', '\x11B', '\a', '\x18', '\x2', '\x2', '\x11B', 
		'\x120', '\x5', '\x12', '\n', '\x2', '\x11C', '\x11D', '\a', '\x15', '\x2', 
		'\x2', '\x11D', '\x11F', '\x5', '\x12', '\n', '\x2', '\x11E', '\x11C', 
		'\x3', '\x2', '\x2', '\x2', '\x11F', '\x122', '\x3', '\x2', '\x2', '\x2', 
		'\x120', '\x11E', '\x3', '\x2', '\x2', '\x2', '\x120', '\x121', '\x3', 
		'\x2', '\x2', '\x2', '\x121', '\x123', '\x3', '\x2', '\x2', '\x2', '\x122', 
		'\x120', '\x3', '\x2', '\x2', '\x2', '\x123', '\x124', '\a', '\x1D', '\x2', 
		'\x2', '\x124', '\x126', '\x3', '\x2', '\x2', '\x2', '\x125', '\x110', 
		'\x3', '\x2', '\x2', '\x2', '\x125', '\x116', '\x3', '\x2', '\x2', '\x2', 
		'\x126', '\'', '\x3', '\x2', '\x2', '\x2', '\x127', '\x128', '\a', '\x13', 
		'\x2', '\x2', '\x128', '\x129', '\a', '\x1C', '\x2', '\x2', '\x129', '\x12A', 
		'\x5', '\xE', '\b', '\x2', '\x12A', '\x12B', '\a', '\x1D', '\x2', '\x2', 
		'\x12B', ')', '\x3', '\x2', '\x2', '\x2', '\x12C', '\x12E', '\a', '\a', 
		'\x2', '\x2', '\x12D', '\x12F', '\x5', '\x12', '\n', '\x2', '\x12E', '\x12D', 
		'\x3', '\x2', '\x2', '\x2', '\x12E', '\x12F', '\x3', '\x2', '\x2', '\x2', 
		'\x12F', '+', '\x3', '\x2', '\x2', '\x2', '\x130', '\x131', '\x5', '\x1E', 
		'\x10', '\x2', '\x131', '\x132', '\a', '\x17', '\x2', '\x2', '\x132', 
		'\x135', '\x3', '\x2', '\x2', '\x2', '\x133', '\x135', '\x5', '\x1A', 
		'\xE', '\x2', '\x134', '\x130', '\x3', '\x2', '\x2', '\x2', '\x134', '\x133', 
		'\x3', '\x2', '\x2', '\x2', '\x135', '-', '\x3', '\x2', '\x2', '\x2', 
		'\x136', '\x137', '\x5', '\x1E', '\x10', '\x2', '\x137', '\x138', '\a', 
		'\x17', '\x2', '\x2', '\x138', '\x13B', '\x3', '\x2', '\x2', '\x2', '\x139', 
		'\x13B', '\x5', '\x1A', '\xE', '\x2', '\x13A', '\x136', '\x3', '\x2', 
		'\x2', '\x2', '\x13A', '\x139', '\x3', '\x2', '\x2', '\x2', '\x13B', '/', 
		'\x3', '\x2', '\x2', '\x2', '\x13C', '\x13D', '\x5', '\n', '\x6', '\x2', 
		'\x13D', '\x13E', '\a', '\"', '\x2', '\x2', '\x13E', '\x13F', '\x5', '\x12', 
		'\n', '\x2', '\x13F', '\x140', '\a', '\x17', '\x2', '\x2', '\x140', '\x14C', 
		'\x3', '\x2', '\x2', '\x2', '\x141', '\x142', '\x5', '\n', '\x6', '\x2', 
		'\x142', '\x146', '\a', '\x18', '\x2', '\x2', '\x143', '\x145', '\x5', 
		'\x10', '\t', '\x2', '\x144', '\x143', '\x3', '\x2', '\x2', '\x2', '\x145', 
		'\x148', '\x3', '\x2', '\x2', '\x2', '\x146', '\x144', '\x3', '\x2', '\x2', 
		'\x2', '\x146', '\x147', '\x3', '\x2', '\x2', '\x2', '\x147', '\x149', 
		'\x3', '\x2', '\x2', '\x2', '\x148', '\x146', '\x3', '\x2', '\x2', '\x2', 
		'\x149', '\x14A', '\a', '\x19', '\x2', '\x2', '\x14A', '\x14C', '\x3', 
		'\x2', '\x2', '\x2', '\x14B', '\x13C', '\x3', '\x2', '\x2', '\x2', '\x14B', 
		'\x141', '\x3', '\x2', '\x2', '\x2', '\x14C', '\x31', '\x3', '\x2', '\x2', 
		'\x2', '\x14D', '\x14E', '\t', '\x3', '\x2', '\x2', '\x14E', '\x33', '\x3', 
		'\x2', '\x2', '\x2', '\x14F', '\x150', '\a', '%', '\x2', '\x2', '\x150', 
		'\x35', '\x3', '\x2', '\x2', '\x2', '\x151', '\x152', '\a', '&', '\x2', 
		'\x2', '\x152', '\x37', '\x3', '\x2', '\x2', '\x2', '\x153', '\x154', 
		'\t', '\x4', '\x2', '\x2', '\x154', '\x39', '\x3', '\x2', '\x2', '\x2', 
		'\x155', '\x156', '\a', '\n', '\x2', '\x2', '\x156', ';', '\x3', '\x2', 
		'\x2', '\x2', '$', '@', '\x43', 'M', 'U', '\x64', 'g', 't', 'w', '\x8A', 
		'\x99', '\x9D', '\xA2', '\xAD', '\xB0', '\xB6', '\xBE', '\xC7', '\xCF', 
		'\xDC', '\xE1', '\xE6', '\xEC', '\xF6', '\xFD', '\x104', '\x106', '\x10D', 
		'\x120', '\x125', '\x12E', '\x134', '\x13A', '\x146', '\x14B',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace MarlinCompiler.Antlr
