//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/Marlin/MarlinCompiler/src\MarlinParser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace MarlinCompiler.Antlr {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public partial class MarlinParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		SINGLE_LINE_COMMENT=1, BLOCK_COMMENT=2, MODULE=3, CLASS=4, STRUCT=5, RETURN=6, 
		NEW=7, NATIVE=8, NULL=9, TRUE=10, FALSE=11, PRIVATE=12, INTERNAL=13, PUBLIC=14, 
		STATIC=15, READONLY=16, SEALED=17, DOT=18, COMMA=19, COLON=20, SEMICOLON=21, 
		LBRACE=22, RBRACE=23, LPAREN=24, RPAREN=25, LBRACKET=26, RBRACKET=27, 
		ASSIGN=28, DOUBLE_QUOTE=29, DOUBLE_COLON=30, ARROW=31, IDENTIFIER=32, 
		INTEGER=33, NORMAL_STRING=34, DOUBLE=35, WHITESPACES=36;
	public const int
		RULE_file = 0, RULE_typeName = 1, RULE_moduleName = 2, RULE_modifier = 3, 
		RULE_expectArgs = 4, RULE_expectArg = 5, RULE_giveArgs = 6, RULE_statement = 7, 
		RULE_expression = 8, RULE_typeDeclaration = 9, RULE_classDeclaration = 10, 
		RULE_structDeclaration = 11, RULE_methodDeclaration = 12, RULE_methodCall = 13, 
		RULE_variableDeclaration = 14, RULE_localVariableDeclaration = 15, RULE_variableAssignment = 16, 
		RULE_memberAccess = 17, RULE_arrayInitializer = 18, RULE_return = 19, 
		RULE_classMember = 20, RULE_structMember = 21, RULE_methodBody = 22, RULE_booleanLiteral = 23, 
		RULE_stringLiteral = 24, RULE_numberLiteral = 25;
	public static readonly string[] ruleNames = {
		"file", "typeName", "moduleName", "modifier", "expectArgs", "expectArg", 
		"giveArgs", "statement", "expression", "typeDeclaration", "classDeclaration", 
		"structDeclaration", "methodDeclaration", "methodCall", "variableDeclaration", 
		"localVariableDeclaration", "variableAssignment", "memberAccess", "arrayInitializer", 
		"return", "classMember", "structMember", "methodBody", "booleanLiteral", 
		"stringLiteral", "numberLiteral"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, "'module'", "'class'", "'struct'", "'return'", "'new'", 
		"'native'", "'null'", "'true'", "'false'", "'private'", "'internal'", 
		"'public'", "'static'", "'readonly'", "'sealed'", "'.'", "','", "':'", 
		"';'", "'{'", "'}'", "'('", "')'", "'['", "']'", "'='", "'\"'", "'::'", 
		"'=>'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "SINGLE_LINE_COMMENT", "BLOCK_COMMENT", "MODULE", "CLASS", "STRUCT", 
		"RETURN", "NEW", "NATIVE", "NULL", "TRUE", "FALSE", "PRIVATE", "INTERNAL", 
		"PUBLIC", "STATIC", "READONLY", "SEALED", "DOT", "COMMA", "COLON", "SEMICOLON", 
		"LBRACE", "RBRACE", "LPAREN", "RPAREN", "LBRACKET", "RBRACKET", "ASSIGN", 
		"DOUBLE_QUOTE", "DOUBLE_COLON", "ARROW", "IDENTIFIER", "INTEGER", "NORMAL_STRING", 
		"DOUBLE", "WHITESPACES"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "MarlinParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static MarlinParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public MarlinParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public MarlinParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class FileContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ModuleNameContext moduleName() {
			return GetRuleContext<ModuleNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeDeclarationContext[] typeDeclaration() {
			return GetRuleContexts<TypeDeclarationContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeDeclarationContext typeDeclaration(int i) {
			return GetRuleContext<TypeDeclarationContext>(i);
		}
		public FileContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_file; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFile(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FileContext file() {
		FileContext _localctx = new FileContext(Context, State);
		EnterRule(_localctx, 0, RULE_file);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 52;
			moduleName();
			State = 56;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << CLASS) | (1L << STRUCT) | (1L << PRIVATE) | (1L << PUBLIC) | (1L << STATIC) | (1L << READONLY) | (1L << SEALED))) != 0)) {
				{
				{
				State = 53;
				typeDeclaration();
				}
				}
				State = 58;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENTIFIER() { return GetTokens(MarlinParser.IDENTIFIER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER(int i) {
			return GetToken(MarlinParser.IDENTIFIER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DOUBLE_COLON() { return GetTokens(MarlinParser.DOUBLE_COLON); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE_COLON(int i) {
			return GetToken(MarlinParser.DOUBLE_COLON, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NATIVE() { return GetToken(MarlinParser.NATIVE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACKET() { return GetToken(MarlinParser.LBRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACKET() { return GetToken(MarlinParser.RBRACKET, 0); }
		public TypeNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeNameContext typeName() {
		return typeName(0);
	}

	private TypeNameContext typeName(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		TypeNameContext _localctx = new TypeNameContext(Context, _parentState);
		TypeNameContext _prevctx = _localctx;
		int _startState = 2;
		EnterRecursionRule(_localctx, 2, RULE_typeName, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 70;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case IDENTIFIER:
				{
				State = 60;
				Match(IDENTIFIER);
				State = 65;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
					if ( _alt==1 ) {
						{
						{
						State = 61;
						Match(DOUBLE_COLON);
						State = 62;
						Match(IDENTIFIER);
						}
						} 
					}
					State = 67;
					ErrorHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
				}
				}
				break;
			case NATIVE:
				{
				State = 68;
				Match(NATIVE);
				State = 69;
				Match(IDENTIFIER);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 77;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new TypeNameContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_typeName);
					State = 72;
					if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
					State = 73;
					Match(LBRACKET);
					State = 74;
					Match(RBRACKET);
					}
					} 
				}
				State = 79;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ModuleNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MODULE() { return GetToken(MarlinParser.MODULE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(MarlinParser.SEMICOLON, 0); }
		public ModuleNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_moduleName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitModuleName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ModuleNameContext moduleName() {
		ModuleNameContext _localctx = new ModuleNameContext(Context, State);
		EnterRule(_localctx, 4, RULE_moduleName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 80;
			Match(MODULE);
			State = 81;
			typeName(0);
			State = 82;
			Match(SEMICOLON);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ModifierContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PRIVATE() { return GetToken(MarlinParser.PRIVATE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PUBLIC() { return GetToken(MarlinParser.PUBLIC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STATIC() { return GetToken(MarlinParser.STATIC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode READONLY() { return GetToken(MarlinParser.READONLY, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEALED() { return GetToken(MarlinParser.SEALED, 0); }
		public ModifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_modifier; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitModifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ModifierContext modifier() {
		ModifierContext _localctx = new ModifierContext(Context, State);
		EnterRule(_localctx, 6, RULE_modifier);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 84;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PRIVATE) | (1L << PUBLIC) | (1L << STATIC) | (1L << READONLY) | (1L << SEALED))) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpectArgsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(MarlinParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(MarlinParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpectArgContext[] expectArg() {
			return GetRuleContexts<ExpectArgContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpectArgContext expectArg(int i) {
			return GetRuleContext<ExpectArgContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(MarlinParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(MarlinParser.COMMA, i);
		}
		public ExpectArgsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expectArgs; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpectArgs(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpectArgsContext expectArgs() {
		ExpectArgsContext _localctx = new ExpectArgsContext(Context, State);
		EnterRule(_localctx, 8, RULE_expectArgs);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 86;
			Match(LPAREN);
			State = 95;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==NATIVE || _la==IDENTIFIER) {
				{
				State = 87;
				expectArg();
				State = 92;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 88;
					Match(COMMA);
					State = 89;
					expectArg();
					}
					}
					State = 94;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 97;
			Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpectArgContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(MarlinParser.IDENTIFIER, 0); }
		public ExpectArgContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expectArg; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpectArg(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpectArgContext expectArg() {
		ExpectArgContext _localctx = new ExpectArgContext(Context, State);
		EnterRule(_localctx, 10, RULE_expectArg);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 99;
			typeName(0);
			State = 100;
			Match(IDENTIFIER);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GiveArgsContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(MarlinParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(MarlinParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(MarlinParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(MarlinParser.COMMA, i);
		}
		public GiveArgsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_giveArgs; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGiveArgs(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public GiveArgsContext giveArgs() {
		GiveArgsContext _localctx = new GiveArgsContext(Context, State);
		EnterRule(_localctx, 12, RULE_giveArgs);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 102;
			Match(LPAREN);
			State = 111;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << NEW) | (1L << NATIVE) | (1L << TRUE) | (1L << FALSE) | (1L << LPAREN) | (1L << IDENTIFIER) | (1L << INTEGER) | (1L << NORMAL_STRING) | (1L << DOUBLE))) != 0)) {
				{
				State = 103;
				expression();
				State = 108;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 104;
					Match(COMMA);
					State = 105;
					expression();
					}
					}
					State = 110;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 113;
			Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StatementContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public MethodCallContext methodCall() {
			return GetRuleContext<MethodCallContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(MarlinParser.SEMICOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public LocalVariableDeclarationContext localVariableDeclaration() {
			return GetRuleContext<LocalVariableDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public VariableAssignmentContext variableAssignment() {
			return GetRuleContext<VariableAssignmentContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ReturnContext @return() {
			return GetRuleContext<ReturnContext>(0);
		}
		public StatementContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_statement; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStatement(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StatementContext statement() {
		StatementContext _localctx = new StatementContext(Context, State);
		EnterRule(_localctx, 14, RULE_statement);
		try {
			State = 127;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,8,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 115;
				methodCall();
				State = 116;
				Match(SEMICOLON);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 118;
				localVariableDeclaration();
				State = 119;
				Match(SEMICOLON);
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 121;
				variableAssignment();
				State = 122;
				Match(SEMICOLON);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 124;
				@return();
				State = 125;
				Match(SEMICOLON);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(MarlinParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(MarlinParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public MethodCallContext methodCall() {
			return GetRuleContext<MethodCallContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemberAccessContext memberAccess() {
			return GetRuleContext<MemberAccessContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public BooleanLiteralContext booleanLiteral() {
			return GetRuleContext<BooleanLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StringLiteralContext stringLiteral() {
			return GetRuleContext<StringLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public NumberLiteralContext numberLiteral() {
			return GetRuleContext<NumberLiteralContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArrayInitializerContext arrayInitializer() {
			return GetRuleContext<ArrayInitializerContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(Context, State);
		EnterRule(_localctx, 16, RULE_expression);
		try {
			State = 139;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,9,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 129;
				Match(LPAREN);
				State = 130;
				expression();
				State = 131;
				Match(RPAREN);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 133;
				methodCall();
				}
				break;
			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 134;
				memberAccess(0);
				}
				break;
			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 135;
				booleanLiteral();
				}
				break;
			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 136;
				stringLiteral();
				}
				break;
			case 6:
				EnterOuterAlt(_localctx, 6);
				{
				State = 137;
				numberLiteral();
				}
				break;
			case 7:
				EnterOuterAlt(_localctx, 7);
				{
				State = 138;
				arrayInitializer();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ClassDeclarationContext classDeclaration() {
			return GetRuleContext<ClassDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StructDeclarationContext structDeclaration() {
			return GetRuleContext<StructDeclarationContext>(0);
		}
		public TypeDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeDeclarationContext typeDeclaration() {
		TypeDeclarationContext _localctx = new TypeDeclarationContext(Context, State);
		EnterRule(_localctx, 18, RULE_typeDeclaration);
		try {
			State = 143;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,10,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 141;
				classDeclaration();
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 142;
				structDeclaration();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClassDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CLASS() { return GetToken(MarlinParser.CLASS, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(MarlinParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(MarlinParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(MarlinParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ModifierContext[] modifier() {
			return GetRuleContexts<ModifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ModifierContext modifier(int i) {
			return GetRuleContext<ModifierContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COLON() { return GetToken(MarlinParser.COLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext[] typeName() {
			return GetRuleContexts<TypeNameContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName(int i) {
			return GetRuleContext<TypeNameContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ClassMemberContext[] classMember() {
			return GetRuleContexts<ClassMemberContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ClassMemberContext classMember(int i) {
			return GetRuleContext<ClassMemberContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(MarlinParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(MarlinParser.COMMA, i);
		}
		public ClassDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_classDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClassDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ClassDeclarationContext classDeclaration() {
		ClassDeclarationContext _localctx = new ClassDeclarationContext(Context, State);
		EnterRule(_localctx, 20, RULE_classDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 148;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PRIVATE) | (1L << PUBLIC) | (1L << STATIC) | (1L << READONLY) | (1L << SEALED))) != 0)) {
				{
				{
				State = 145;
				modifier();
				}
				}
				State = 150;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 151;
			Match(CLASS);
			State = 152;
			Match(IDENTIFIER);
			State = 162;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==COLON) {
				{
				State = 153;
				Match(COLON);
				State = 154;
				typeName(0);
				State = 159;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 155;
					Match(COMMA);
					State = 156;
					typeName(0);
					}
					}
					State = 161;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 164;
			Match(LBRACE);
			State = 168;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << NATIVE) | (1L << PRIVATE) | (1L << PUBLIC) | (1L << STATIC) | (1L << READONLY) | (1L << SEALED) | (1L << IDENTIFIER))) != 0)) {
				{
				{
				State = 165;
				classMember();
				}
				}
				State = 170;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 171;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StructDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRUCT() { return GetToken(MarlinParser.STRUCT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(MarlinParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(MarlinParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(MarlinParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ModifierContext[] modifier() {
			return GetRuleContexts<ModifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ModifierContext modifier(int i) {
			return GetRuleContext<ModifierContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public StructMemberContext[] structMember() {
			return GetRuleContexts<StructMemberContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StructMemberContext structMember(int i) {
			return GetRuleContext<StructMemberContext>(i);
		}
		public StructDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_structDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStructDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StructDeclarationContext structDeclaration() {
		StructDeclarationContext _localctx = new StructDeclarationContext(Context, State);
		EnterRule(_localctx, 22, RULE_structDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 176;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PRIVATE) | (1L << PUBLIC) | (1L << STATIC) | (1L << READONLY) | (1L << SEALED))) != 0)) {
				{
				{
				State = 173;
				modifier();
				}
				}
				State = 178;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 179;
			Match(STRUCT);
			State = 180;
			Match(IDENTIFIER);
			State = 181;
			Match(LBRACE);
			State = 185;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << NATIVE) | (1L << PRIVATE) | (1L << PUBLIC) | (1L << STATIC) | (1L << READONLY) | (1L << SEALED) | (1L << IDENTIFIER))) != 0)) {
				{
				{
				State = 182;
				structMember();
				}
				}
				State = 187;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 188;
			Match(RBRACE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MethodDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(MarlinParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public MethodBodyContext methodBody() {
			return GetRuleContext<MethodBodyContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ModifierContext[] modifier() {
			return GetRuleContexts<ModifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ModifierContext modifier(int i) {
			return GetRuleContext<ModifierContext>(i);
		}
		public MethodDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_methodDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMethodDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MethodDeclarationContext methodDeclaration() {
		MethodDeclarationContext _localctx = new MethodDeclarationContext(Context, State);
		EnterRule(_localctx, 24, RULE_methodDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 193;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PRIVATE) | (1L << PUBLIC) | (1L << STATIC) | (1L << READONLY) | (1L << SEALED))) != 0)) {
				{
				{
				State = 190;
				modifier();
				}
				}
				State = 195;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 196;
			typeName(0);
			State = 197;
			Match(IDENTIFIER);
			State = 198;
			methodBody();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MethodCallContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public MemberAccessContext memberAccess() {
			return GetRuleContext<MemberAccessContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public GiveArgsContext giveArgs() {
			return GetRuleContext<GiveArgsContext>(0);
		}
		public MethodCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_methodCall; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMethodCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MethodCallContext methodCall() {
		MethodCallContext _localctx = new MethodCallContext(Context, State);
		EnterRule(_localctx, 26, RULE_methodCall);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 200;
			memberAccess(0);
			State = 201;
			giveArgs();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(MarlinParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ModifierContext[] modifier() {
			return GetRuleContexts<ModifierContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ModifierContext modifier(int i) {
			return GetRuleContext<ModifierContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(MarlinParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public VariableDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableDeclarationContext variableDeclaration() {
		VariableDeclarationContext _localctx = new VariableDeclarationContext(Context, State);
		EnterRule(_localctx, 28, RULE_variableDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 206;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << PRIVATE) | (1L << PUBLIC) | (1L << STATIC) | (1L << READONLY) | (1L << SEALED))) != 0)) {
				{
				{
				State = 203;
				modifier();
				}
				}
				State = 208;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 209;
			typeName(0);
			State = 210;
			Match(IDENTIFIER);
			State = 213;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ASSIGN) {
				{
				State = 211;
				Match(ASSIGN);
				State = 212;
				expression();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LocalVariableDeclarationContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(MarlinParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(MarlinParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public LocalVariableDeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_localVariableDeclaration; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLocalVariableDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LocalVariableDeclarationContext localVariableDeclaration() {
		LocalVariableDeclarationContext _localctx = new LocalVariableDeclarationContext(Context, State);
		EnterRule(_localctx, 30, RULE_localVariableDeclaration);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 215;
			typeName(0);
			State = 216;
			Match(IDENTIFIER);
			State = 219;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if (_la==ASSIGN) {
				{
				State = 217;
				Match(ASSIGN);
				State = 218;
				expression();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VariableAssignmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public MemberAccessContext memberAccess() {
			return GetRuleContext<MemberAccessContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ASSIGN() { return GetToken(MarlinParser.ASSIGN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public VariableAssignmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_variableAssignment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVariableAssignment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VariableAssignmentContext variableAssignment() {
		VariableAssignmentContext _localctx = new VariableAssignmentContext(Context, State);
		EnterRule(_localctx, 32, RULE_variableAssignment);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 221;
			memberAccess(0);
			State = 222;
			Match(ASSIGN);
			State = 223;
			expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MemberAccessContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(MarlinParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT() { return GetToken(MarlinParser.DOT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACKET() { return GetToken(MarlinParser.LBRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACKET() { return GetToken(MarlinParser.RBRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public MemberAccessContext[] memberAccess() {
			return GetRuleContexts<MemberAccessContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public MemberAccessContext memberAccess(int i) {
			return GetRuleContext<MemberAccessContext>(i);
		}
		public MemberAccessContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_memberAccess; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMemberAccess(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MemberAccessContext memberAccess() {
		return memberAccess(0);
	}

	private MemberAccessContext memberAccess(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		MemberAccessContext _localctx = new MemberAccessContext(Context, _parentState);
		MemberAccessContext _prevctx = _localctx;
		int _startState = 34;
		EnterRecursionRule(_localctx, 34, RULE_memberAccess, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 245;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,24,Context) ) {
			case 1:
				{
				State = 229;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,21,Context) ) {
				case 1:
					{
					State = 226;
					typeName(0);
					State = 227;
					Match(DOT);
					}
					break;
				}
				State = 231;
				Match(IDENTIFIER);
				State = 236;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,22,Context) ) {
				case 1:
					{
					State = 232;
					Match(LBRACKET);
					State = 233;
					expression();
					State = 234;
					Match(RBRACKET);
					}
					break;
				}
				}
				break;
			case 2:
				{
				State = 238;
				Match(IDENTIFIER);
				State = 243;
				ErrorHandler.Sync(this);
				switch ( Interpreter.AdaptivePredict(TokenStream,23,Context) ) {
				case 1:
					{
					State = 239;
					Match(LBRACKET);
					State = 240;
					expression();
					State = 241;
					Match(RBRACKET);
					}
					break;
				}
				}
				break;
			}
			Context.Stop = TokenStream.LT(-1);
			State = 252;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,25,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new MemberAccessContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_memberAccess);
					State = 247;
					if (!(Precpred(Context, 2))) throw new FailedPredicateException(this, "Precpred(Context, 2)");
					State = 248;
					Match(DOT);
					State = 249;
					memberAccess(3);
					}
					} 
				}
				State = 254;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,25,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ArrayInitializerContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NEW() { return GetToken(MarlinParser.NEW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACKET() { return GetToken(MarlinParser.LBRACKET, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] RBRACKET() { return GetTokens(MarlinParser.RBRACKET); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACKET(int i) {
			return GetToken(MarlinParser.RBRACKET, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(MarlinParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(MarlinParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(MarlinParser.COMMA, i);
		}
		public ArrayInitializerContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arrayInitializer; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrayInitializer(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArrayInitializerContext arrayInitializer() {
		ArrayInitializerContext _localctx = new ArrayInitializerContext(Context, State);
		EnterRule(_localctx, 36, RULE_arrayInitializer);
		int _la;
		try {
			State = 276;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,27,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 255;
				Match(NEW);
				State = 256;
				typeName(0);
				State = 257;
				Match(LBRACKET);
				State = 258;
				expression();
				State = 259;
				Match(RBRACKET);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 261;
				Match(NEW);
				State = 262;
				typeName(0);
				State = 263;
				Match(LBRACKET);
				State = 264;
				Match(RBRACKET);
				State = 265;
				Match(LBRACE);
				State = 266;
				expression();
				State = 271;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 267;
					Match(COMMA);
					State = 268;
					expression();
					}
					}
					State = 273;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 274;
				Match(RBRACKET);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReturnContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RETURN() { return GetToken(MarlinParser.RETURN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ReturnContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_return; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReturn(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ReturnContext @return() {
		ReturnContext _localctx = new ReturnContext(Context, State);
		EnterRule(_localctx, 38, RULE_return);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 278;
			Match(RETURN);
			State = 280;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << NEW) | (1L << NATIVE) | (1L << TRUE) | (1L << FALSE) | (1L << LPAREN) | (1L << IDENTIFIER) | (1L << INTEGER) | (1L << NORMAL_STRING) | (1L << DOUBLE))) != 0)) {
				{
				State = 279;
				expression();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ClassMemberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VariableDeclarationContext variableDeclaration() {
			return GetRuleContext<VariableDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(MarlinParser.SEMICOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public MethodDeclarationContext methodDeclaration() {
			return GetRuleContext<MethodDeclarationContext>(0);
		}
		public ClassMemberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_classMember; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitClassMember(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ClassMemberContext classMember() {
		ClassMemberContext _localctx = new ClassMemberContext(Context, State);
		EnterRule(_localctx, 40, RULE_classMember);
		try {
			State = 286;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,29,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 282;
				variableDeclaration();
				State = 283;
				Match(SEMICOLON);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 285;
				methodDeclaration();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StructMemberContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public VariableDeclarationContext variableDeclaration() {
			return GetRuleContext<VariableDeclarationContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(MarlinParser.SEMICOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public MethodDeclarationContext methodDeclaration() {
			return GetRuleContext<MethodDeclarationContext>(0);
		}
		public StructMemberContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_structMember; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStructMember(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StructMemberContext structMember() {
		StructMemberContext _localctx = new StructMemberContext(Context, State);
		EnterRule(_localctx, 42, RULE_structMember);
		try {
			State = 292;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,30,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 288;
				variableDeclaration();
				State = 289;
				Match(SEMICOLON);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 291;
				methodDeclaration();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MethodBodyContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExpectArgsContext expectArgs() {
			return GetRuleContext<ExpectArgsContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ARROW() { return GetToken(MarlinParser.ARROW, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SEMICOLON() { return GetToken(MarlinParser.SEMICOLON, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LBRACE() { return GetToken(MarlinParser.LBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RBRACE() { return GetToken(MarlinParser.RBRACE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext[] statement() {
			return GetRuleContexts<StatementContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public StatementContext statement(int i) {
			return GetRuleContext<StatementContext>(i);
		}
		public MethodBodyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_methodBody; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMethodBody(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MethodBodyContext methodBody() {
		MethodBodyContext _localctx = new MethodBodyContext(Context, State);
		EnterRule(_localctx, 44, RULE_methodBody);
		int _la;
		try {
			State = 309;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,32,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 294;
				expectArgs();
				State = 295;
				Match(ARROW);
				State = 296;
				expression();
				State = 297;
				Match(SEMICOLON);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 299;
				expectArgs();
				State = 300;
				Match(LBRACE);
				State = 304;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << RETURN) | (1L << NATIVE) | (1L << IDENTIFIER))) != 0)) {
					{
					{
					State = 301;
					statement();
					}
					}
					State = 306;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				State = 307;
				Match(RBRACE);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class BooleanLiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TRUE() { return GetToken(MarlinParser.TRUE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FALSE() { return GetToken(MarlinParser.FALSE, 0); }
		public BooleanLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_booleanLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBooleanLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BooleanLiteralContext booleanLiteral() {
		BooleanLiteralContext _localctx = new BooleanLiteralContext(Context, State);
		EnterRule(_localctx, 46, RULE_booleanLiteral);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 311;
			_la = TokenStream.LA(1);
			if ( !(_la==TRUE || _la==FALSE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StringLiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NORMAL_STRING() { return GetToken(MarlinParser.NORMAL_STRING, 0); }
		public StringLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stringLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStringLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StringLiteralContext stringLiteral() {
		StringLiteralContext _localctx = new StringLiteralContext(Context, State);
		EnterRule(_localctx, 48, RULE_stringLiteral);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 313;
			Match(NORMAL_STRING);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumberLiteralContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTEGER() { return GetToken(MarlinParser.INTEGER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOUBLE() { return GetToken(MarlinParser.DOUBLE, 0); }
		public NumberLiteralContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_numberLiteral; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IMarlinParserVisitor<TResult> typedVisitor = visitor as IMarlinParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNumberLiteral(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumberLiteralContext numberLiteral() {
		NumberLiteralContext _localctx = new NumberLiteralContext(Context, State);
		EnterRule(_localctx, 50, RULE_numberLiteral);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 315;
			_la = TokenStream.LA(1);
			if ( !(_la==INTEGER || _la==DOUBLE) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 1: return typeName_sempred((TypeNameContext)_localctx, predIndex);
		case 17: return memberAccess_sempred((MemberAccessContext)_localctx, predIndex);
		}
		return true;
	}
	private bool typeName_sempred(TypeNameContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 3);
		}
		return true;
	}
	private bool memberAccess_sempred(MemberAccessContext _localctx, int predIndex) {
		switch (predIndex) {
		case 1: return Precpred(Context, 2);
		}
		return true;
	}

	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x3', '&', '\x140', '\x4', '\x2', '\t', '\x2', '\x4', '\x3', 
		'\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', '\x5', '\x4', 
		'\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', '\t', '\b', 
		'\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', '\t', '\v', 
		'\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', '\t', 
		'\xE', '\x4', '\xF', '\t', '\xF', '\x4', '\x10', '\t', '\x10', '\x4', 
		'\x11', '\t', '\x11', '\x4', '\x12', '\t', '\x12', '\x4', '\x13', '\t', 
		'\x13', '\x4', '\x14', '\t', '\x14', '\x4', '\x15', '\t', '\x15', '\x4', 
		'\x16', '\t', '\x16', '\x4', '\x17', '\t', '\x17', '\x4', '\x18', '\t', 
		'\x18', '\x4', '\x19', '\t', '\x19', '\x4', '\x1A', '\t', '\x1A', '\x4', 
		'\x1B', '\t', '\x1B', '\x3', '\x2', '\x3', '\x2', '\a', '\x2', '\x39', 
		'\n', '\x2', '\f', '\x2', '\xE', '\x2', '<', '\v', '\x2', '\x3', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\a', '\x3', '\x42', '\n', '\x3', 
		'\f', '\x3', '\xE', '\x3', '\x45', '\v', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\x5', '\x3', 'I', '\n', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', '\x3', 
		'\a', '\x3', 'N', '\n', '\x3', '\f', '\x3', '\xE', '\x3', 'Q', '\v', '\x3', 
		'\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\x3', '\x5', 
		'\x3', '\x5', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', '\x6', 
		'\a', '\x6', ']', '\n', '\x6', '\f', '\x6', '\xE', '\x6', '`', '\v', '\x6', 
		'\x5', '\x6', '\x62', '\n', '\x6', '\x3', '\x6', '\x3', '\x6', '\x3', 
		'\a', '\x3', '\a', '\x3', '\a', '\x3', '\b', '\x3', '\b', '\x3', '\b', 
		'\x3', '\b', '\a', '\b', 'm', '\n', '\b', '\f', '\b', '\xE', '\b', 'p', 
		'\v', '\b', '\x5', '\b', 'r', '\n', '\b', '\x3', '\b', '\x3', '\b', '\x3', 
		'\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', 
		'\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\x3', 
		'\t', '\x5', '\t', '\x82', '\n', '\t', '\x3', '\n', '\x3', '\n', '\x3', 
		'\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\x5', '\n', '\x8E', '\n', '\n', '\x3', '\v', 
		'\x3', '\v', '\x5', '\v', '\x92', '\n', '\v', '\x3', '\f', '\a', '\f', 
		'\x95', '\n', '\f', '\f', '\f', '\xE', '\f', '\x98', '\v', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\a', '\f', '\xA0', '\n', '\f', '\f', '\f', '\xE', '\f', '\xA3', '\v', 
		'\f', '\x5', '\f', '\xA5', '\n', '\f', '\x3', '\f', '\x3', '\f', '\a', 
		'\f', '\xA9', '\n', '\f', '\f', '\f', '\xE', '\f', '\xAC', '\v', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\r', '\a', '\r', '\xB1', '\n', '\r', 
		'\f', '\r', '\xE', '\r', '\xB4', '\v', '\r', '\x3', '\r', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\a', '\r', '\xBA', '\n', '\r', '\f', '\r', 
		'\xE', '\r', '\xBD', '\v', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', 
		'\a', '\xE', '\xC2', '\n', '\xE', '\f', '\xE', '\xE', '\xE', '\xC5', '\v', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xF', '\x3', '\xF', '\x3', '\xF', '\x3', '\x10', '\a', '\x10', '\xCF', 
		'\n', '\x10', '\f', '\x10', '\xE', '\x10', '\xD2', '\v', '\x10', '\x3', 
		'\x10', '\x3', '\x10', '\x3', '\x10', '\x3', '\x10', '\x5', '\x10', '\xD8', 
		'\n', '\x10', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', '\x3', '\x11', 
		'\x5', '\x11', '\xDE', '\n', '\x11', '\x3', '\x12', '\x3', '\x12', '\x3', 
		'\x12', '\x3', '\x12', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x5', '\x13', '\xE8', '\n', '\x13', '\x3', '\x13', '\x3', '\x13', 
		'\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x5', '\x13', '\xEF', '\n', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\x3', 
		'\x13', '\x5', '\x13', '\xF6', '\n', '\x13', '\x5', '\x13', '\xF8', '\n', 
		'\x13', '\x3', '\x13', '\x3', '\x13', '\x3', '\x13', '\a', '\x13', '\xFD', 
		'\n', '\x13', '\f', '\x13', '\xE', '\x13', '\x100', '\v', '\x13', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x3', '\x14', '\x3', '\x14', '\a', '\x14', '\x110', 
		'\n', '\x14', '\f', '\x14', '\xE', '\x14', '\x113', '\v', '\x14', '\x3', 
		'\x14', '\x3', '\x14', '\x5', '\x14', '\x117', '\n', '\x14', '\x3', '\x15', 
		'\x3', '\x15', '\x5', '\x15', '\x11B', '\n', '\x15', '\x3', '\x16', '\x3', 
		'\x16', '\x3', '\x16', '\x3', '\x16', '\x5', '\x16', '\x121', '\n', '\x16', 
		'\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x3', '\x17', '\x5', '\x17', 
		'\x127', '\n', '\x17', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\x3', '\x18', '\a', 
		'\x18', '\x131', '\n', '\x18', '\f', '\x18', '\xE', '\x18', '\x134', '\v', 
		'\x18', '\x3', '\x18', '\x3', '\x18', '\x5', '\x18', '\x138', '\n', '\x18', 
		'\x3', '\x19', '\x3', '\x19', '\x3', '\x1A', '\x3', '\x1A', '\x3', '\x1B', 
		'\x3', '\x1B', '\x3', '\x1B', '\x2', '\x4', '\x4', '$', '\x1C', '\x2', 
		'\x4', '\x6', '\b', '\n', '\f', '\xE', '\x10', '\x12', '\x14', '\x16', 
		'\x18', '\x1A', '\x1C', '\x1E', ' ', '\"', '$', '&', '(', '*', ',', '.', 
		'\x30', '\x32', '\x34', '\x2', '\x5', '\x4', '\x2', '\xE', '\xE', '\x10', 
		'\x13', '\x3', '\x2', '\f', '\r', '\x4', '\x2', '#', '#', '%', '%', '\x2', 
		'\x14D', '\x2', '\x36', '\x3', '\x2', '\x2', '\x2', '\x4', 'H', '\x3', 
		'\x2', '\x2', '\x2', '\x6', 'R', '\x3', '\x2', '\x2', '\x2', '\b', 'V', 
		'\x3', '\x2', '\x2', '\x2', '\n', 'X', '\x3', '\x2', '\x2', '\x2', '\f', 
		'\x65', '\x3', '\x2', '\x2', '\x2', '\xE', 'h', '\x3', '\x2', '\x2', '\x2', 
		'\x10', '\x81', '\x3', '\x2', '\x2', '\x2', '\x12', '\x8D', '\x3', '\x2', 
		'\x2', '\x2', '\x14', '\x91', '\x3', '\x2', '\x2', '\x2', '\x16', '\x96', 
		'\x3', '\x2', '\x2', '\x2', '\x18', '\xB2', '\x3', '\x2', '\x2', '\x2', 
		'\x1A', '\xC3', '\x3', '\x2', '\x2', '\x2', '\x1C', '\xCA', '\x3', '\x2', 
		'\x2', '\x2', '\x1E', '\xD0', '\x3', '\x2', '\x2', '\x2', ' ', '\xD9', 
		'\x3', '\x2', '\x2', '\x2', '\"', '\xDF', '\x3', '\x2', '\x2', '\x2', 
		'$', '\xF7', '\x3', '\x2', '\x2', '\x2', '&', '\x116', '\x3', '\x2', '\x2', 
		'\x2', '(', '\x118', '\x3', '\x2', '\x2', '\x2', '*', '\x120', '\x3', 
		'\x2', '\x2', '\x2', ',', '\x126', '\x3', '\x2', '\x2', '\x2', '.', '\x137', 
		'\x3', '\x2', '\x2', '\x2', '\x30', '\x139', '\x3', '\x2', '\x2', '\x2', 
		'\x32', '\x13B', '\x3', '\x2', '\x2', '\x2', '\x34', '\x13D', '\x3', '\x2', 
		'\x2', '\x2', '\x36', ':', '\x5', '\x6', '\x4', '\x2', '\x37', '\x39', 
		'\x5', '\x14', '\v', '\x2', '\x38', '\x37', '\x3', '\x2', '\x2', '\x2', 
		'\x39', '<', '\x3', '\x2', '\x2', '\x2', ':', '\x38', '\x3', '\x2', '\x2', 
		'\x2', ':', ';', '\x3', '\x2', '\x2', '\x2', ';', '\x3', '\x3', '\x2', 
		'\x2', '\x2', '<', ':', '\x3', '\x2', '\x2', '\x2', '=', '>', '\b', '\x3', 
		'\x1', '\x2', '>', '\x43', '\a', '\"', '\x2', '\x2', '?', '@', '\a', ' ', 
		'\x2', '\x2', '@', '\x42', '\a', '\"', '\x2', '\x2', '\x41', '?', '\x3', 
		'\x2', '\x2', '\x2', '\x42', '\x45', '\x3', '\x2', '\x2', '\x2', '\x43', 
		'\x41', '\x3', '\x2', '\x2', '\x2', '\x43', '\x44', '\x3', '\x2', '\x2', 
		'\x2', '\x44', 'I', '\x3', '\x2', '\x2', '\x2', '\x45', '\x43', '\x3', 
		'\x2', '\x2', '\x2', '\x46', 'G', '\a', '\n', '\x2', '\x2', 'G', 'I', 
		'\a', '\"', '\x2', '\x2', 'H', '=', '\x3', '\x2', '\x2', '\x2', 'H', '\x46', 
		'\x3', '\x2', '\x2', '\x2', 'I', 'O', '\x3', '\x2', '\x2', '\x2', 'J', 
		'K', '\f', '\x5', '\x2', '\x2', 'K', 'L', '\a', '\x1C', '\x2', '\x2', 
		'L', 'N', '\a', '\x1D', '\x2', '\x2', 'M', 'J', '\x3', '\x2', '\x2', '\x2', 
		'N', 'Q', '\x3', '\x2', '\x2', '\x2', 'O', 'M', '\x3', '\x2', '\x2', '\x2', 
		'O', 'P', '\x3', '\x2', '\x2', '\x2', 'P', '\x5', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'O', '\x3', '\x2', '\x2', '\x2', 'R', 'S', '\a', '\x5', '\x2', 
		'\x2', 'S', 'T', '\x5', '\x4', '\x3', '\x2', 'T', 'U', '\a', '\x17', '\x2', 
		'\x2', 'U', '\a', '\x3', '\x2', '\x2', '\x2', 'V', 'W', '\t', '\x2', '\x2', 
		'\x2', 'W', '\t', '\x3', '\x2', '\x2', '\x2', 'X', '\x61', '\a', '\x1A', 
		'\x2', '\x2', 'Y', '^', '\x5', '\f', '\a', '\x2', 'Z', '[', '\a', '\x15', 
		'\x2', '\x2', '[', ']', '\x5', '\f', '\a', '\x2', '\\', 'Z', '\x3', '\x2', 
		'\x2', '\x2', ']', '`', '\x3', '\x2', '\x2', '\x2', '^', '\\', '\x3', 
		'\x2', '\x2', '\x2', '^', '_', '\x3', '\x2', '\x2', '\x2', '_', '\x62', 
		'\x3', '\x2', '\x2', '\x2', '`', '^', '\x3', '\x2', '\x2', '\x2', '\x61', 
		'Y', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\x3', '\x2', '\x2', 
		'\x2', '\x62', '\x63', '\x3', '\x2', '\x2', '\x2', '\x63', '\x64', '\a', 
		'\x1B', '\x2', '\x2', '\x64', '\v', '\x3', '\x2', '\x2', '\x2', '\x65', 
		'\x66', '\x5', '\x4', '\x3', '\x2', '\x66', 'g', '\a', '\"', '\x2', '\x2', 
		'g', '\r', '\x3', '\x2', '\x2', '\x2', 'h', 'q', '\a', '\x1A', '\x2', 
		'\x2', 'i', 'n', '\x5', '\x12', '\n', '\x2', 'j', 'k', '\a', '\x15', '\x2', 
		'\x2', 'k', 'm', '\x5', '\x12', '\n', '\x2', 'l', 'j', '\x3', '\x2', '\x2', 
		'\x2', 'm', 'p', '\x3', '\x2', '\x2', '\x2', 'n', 'l', '\x3', '\x2', '\x2', 
		'\x2', 'n', 'o', '\x3', '\x2', '\x2', '\x2', 'o', 'r', '\x3', '\x2', '\x2', 
		'\x2', 'p', 'n', '\x3', '\x2', '\x2', '\x2', 'q', 'i', '\x3', '\x2', '\x2', 
		'\x2', 'q', 'r', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\x3', '\x2', '\x2', 
		'\x2', 's', 't', '\a', '\x1B', '\x2', '\x2', 't', '\xF', '\x3', '\x2', 
		'\x2', '\x2', 'u', 'v', '\x5', '\x1C', '\xF', '\x2', 'v', 'w', '\a', '\x17', 
		'\x2', '\x2', 'w', '\x82', '\x3', '\x2', '\x2', '\x2', 'x', 'y', '\x5', 
		' ', '\x11', '\x2', 'y', 'z', '\a', '\x17', '\x2', '\x2', 'z', '\x82', 
		'\x3', '\x2', '\x2', '\x2', '{', '|', '\x5', '\"', '\x12', '\x2', '|', 
		'}', '\a', '\x17', '\x2', '\x2', '}', '\x82', '\x3', '\x2', '\x2', '\x2', 
		'~', '\x7F', '\x5', '(', '\x15', '\x2', '\x7F', '\x80', '\a', '\x17', 
		'\x2', '\x2', '\x80', '\x82', '\x3', '\x2', '\x2', '\x2', '\x81', 'u', 
		'\x3', '\x2', '\x2', '\x2', '\x81', 'x', '\x3', '\x2', '\x2', '\x2', '\x81', 
		'{', '\x3', '\x2', '\x2', '\x2', '\x81', '~', '\x3', '\x2', '\x2', '\x2', 
		'\x82', '\x11', '\x3', '\x2', '\x2', '\x2', '\x83', '\x84', '\a', '\x1A', 
		'\x2', '\x2', '\x84', '\x85', '\x5', '\x12', '\n', '\x2', '\x85', '\x86', 
		'\a', '\x1B', '\x2', '\x2', '\x86', '\x8E', '\x3', '\x2', '\x2', '\x2', 
		'\x87', '\x8E', '\x5', '\x1C', '\xF', '\x2', '\x88', '\x8E', '\x5', '$', 
		'\x13', '\x2', '\x89', '\x8E', '\x5', '\x30', '\x19', '\x2', '\x8A', '\x8E', 
		'\x5', '\x32', '\x1A', '\x2', '\x8B', '\x8E', '\x5', '\x34', '\x1B', '\x2', 
		'\x8C', '\x8E', '\x5', '&', '\x14', '\x2', '\x8D', '\x83', '\x3', '\x2', 
		'\x2', '\x2', '\x8D', '\x87', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x88', 
		'\x3', '\x2', '\x2', '\x2', '\x8D', '\x89', '\x3', '\x2', '\x2', '\x2', 
		'\x8D', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8B', '\x3', '\x2', 
		'\x2', '\x2', '\x8D', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x8E', '\x13', 
		'\x3', '\x2', '\x2', '\x2', '\x8F', '\x92', '\x5', '\x16', '\f', '\x2', 
		'\x90', '\x92', '\x5', '\x18', '\r', '\x2', '\x91', '\x8F', '\x3', '\x2', 
		'\x2', '\x2', '\x91', '\x90', '\x3', '\x2', '\x2', '\x2', '\x92', '\x15', 
		'\x3', '\x2', '\x2', '\x2', '\x93', '\x95', '\x5', '\b', '\x5', '\x2', 
		'\x94', '\x93', '\x3', '\x2', '\x2', '\x2', '\x95', '\x98', '\x3', '\x2', 
		'\x2', '\x2', '\x96', '\x94', '\x3', '\x2', '\x2', '\x2', '\x96', '\x97', 
		'\x3', '\x2', '\x2', '\x2', '\x97', '\x99', '\x3', '\x2', '\x2', '\x2', 
		'\x98', '\x96', '\x3', '\x2', '\x2', '\x2', '\x99', '\x9A', '\a', '\x6', 
		'\x2', '\x2', '\x9A', '\xA4', '\a', '\"', '\x2', '\x2', '\x9B', '\x9C', 
		'\a', '\x16', '\x2', '\x2', '\x9C', '\xA1', '\x5', '\x4', '\x3', '\x2', 
		'\x9D', '\x9E', '\a', '\x15', '\x2', '\x2', '\x9E', '\xA0', '\x5', '\x4', 
		'\x3', '\x2', '\x9F', '\x9D', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA3', 
		'\x3', '\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', '\x2', '\x2', '\x2', 
		'\xA1', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA2', '\xA5', '\x3', '\x2', 
		'\x2', '\x2', '\xA3', '\xA1', '\x3', '\x2', '\x2', '\x2', '\xA4', '\x9B', 
		'\x3', '\x2', '\x2', '\x2', '\xA4', '\xA5', '\x3', '\x2', '\x2', '\x2', 
		'\xA5', '\xA6', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xAA', '\a', '\x18', 
		'\x2', '\x2', '\xA7', '\xA9', '\x5', '*', '\x16', '\x2', '\xA8', '\xA7', 
		'\x3', '\x2', '\x2', '\x2', '\xA9', '\xAC', '\x3', '\x2', '\x2', '\x2', 
		'\xAA', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAB', '\x3', '\x2', 
		'\x2', '\x2', '\xAB', '\xAD', '\x3', '\x2', '\x2', '\x2', '\xAC', '\xAA', 
		'\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\a', '\x19', '\x2', '\x2', 
		'\xAE', '\x17', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xB1', '\x5', '\b', 
		'\x5', '\x2', '\xB0', '\xAF', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB4', 
		'\x3', '\x2', '\x2', '\x2', '\xB2', '\xB0', '\x3', '\x2', '\x2', '\x2', 
		'\xB2', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB5', '\x3', '\x2', 
		'\x2', '\x2', '\xB4', '\xB2', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', 
		'\a', '\a', '\x2', '\x2', '\xB6', '\xB7', '\a', '\"', '\x2', '\x2', '\xB7', 
		'\xBB', '\a', '\x18', '\x2', '\x2', '\xB8', '\xBA', '\x5', ',', '\x17', 
		'\x2', '\xB9', '\xB8', '\x3', '\x2', '\x2', '\x2', '\xBA', '\xBD', '\x3', 
		'\x2', '\x2', '\x2', '\xBB', '\xB9', '\x3', '\x2', '\x2', '\x2', '\xBB', 
		'\xBC', '\x3', '\x2', '\x2', '\x2', '\xBC', '\xBE', '\x3', '\x2', '\x2', 
		'\x2', '\xBD', '\xBB', '\x3', '\x2', '\x2', '\x2', '\xBE', '\xBF', '\a', 
		'\x19', '\x2', '\x2', '\xBF', '\x19', '\x3', '\x2', '\x2', '\x2', '\xC0', 
		'\xC2', '\x5', '\b', '\x5', '\x2', '\xC1', '\xC0', '\x3', '\x2', '\x2', 
		'\x2', '\xC2', '\xC5', '\x3', '\x2', '\x2', '\x2', '\xC3', '\xC1', '\x3', 
		'\x2', '\x2', '\x2', '\xC3', '\xC4', '\x3', '\x2', '\x2', '\x2', '\xC4', 
		'\xC6', '\x3', '\x2', '\x2', '\x2', '\xC5', '\xC3', '\x3', '\x2', '\x2', 
		'\x2', '\xC6', '\xC7', '\x5', '\x4', '\x3', '\x2', '\xC7', '\xC8', '\a', 
		'\"', '\x2', '\x2', '\xC8', '\xC9', '\x5', '.', '\x18', '\x2', '\xC9', 
		'\x1B', '\x3', '\x2', '\x2', '\x2', '\xCA', '\xCB', '\x5', '$', '\x13', 
		'\x2', '\xCB', '\xCC', '\x5', '\xE', '\b', '\x2', '\xCC', '\x1D', '\x3', 
		'\x2', '\x2', '\x2', '\xCD', '\xCF', '\x5', '\b', '\x5', '\x2', '\xCE', 
		'\xCD', '\x3', '\x2', '\x2', '\x2', '\xCF', '\xD2', '\x3', '\x2', '\x2', 
		'\x2', '\xD0', '\xCE', '\x3', '\x2', '\x2', '\x2', '\xD0', '\xD1', '\x3', 
		'\x2', '\x2', '\x2', '\xD1', '\xD3', '\x3', '\x2', '\x2', '\x2', '\xD2', 
		'\xD0', '\x3', '\x2', '\x2', '\x2', '\xD3', '\xD4', '\x5', '\x4', '\x3', 
		'\x2', '\xD4', '\xD7', '\a', '\"', '\x2', '\x2', '\xD5', '\xD6', '\a', 
		'\x1E', '\x2', '\x2', '\xD6', '\xD8', '\x5', '\x12', '\n', '\x2', '\xD7', 
		'\xD5', '\x3', '\x2', '\x2', '\x2', '\xD7', '\xD8', '\x3', '\x2', '\x2', 
		'\x2', '\xD8', '\x1F', '\x3', '\x2', '\x2', '\x2', '\xD9', '\xDA', '\x5', 
		'\x4', '\x3', '\x2', '\xDA', '\xDD', '\a', '\"', '\x2', '\x2', '\xDB', 
		'\xDC', '\a', '\x1E', '\x2', '\x2', '\xDC', '\xDE', '\x5', '\x12', '\n', 
		'\x2', '\xDD', '\xDB', '\x3', '\x2', '\x2', '\x2', '\xDD', '\xDE', '\x3', 
		'\x2', '\x2', '\x2', '\xDE', '!', '\x3', '\x2', '\x2', '\x2', '\xDF', 
		'\xE0', '\x5', '$', '\x13', '\x2', '\xE0', '\xE1', '\a', '\x1E', '\x2', 
		'\x2', '\xE1', '\xE2', '\x5', '\x12', '\n', '\x2', '\xE2', '#', '\x3', 
		'\x2', '\x2', '\x2', '\xE3', '\xE7', '\b', '\x13', '\x1', '\x2', '\xE4', 
		'\xE5', '\x5', '\x4', '\x3', '\x2', '\xE5', '\xE6', '\a', '\x14', '\x2', 
		'\x2', '\xE6', '\xE8', '\x3', '\x2', '\x2', '\x2', '\xE7', '\xE4', '\x3', 
		'\x2', '\x2', '\x2', '\xE7', '\xE8', '\x3', '\x2', '\x2', '\x2', '\xE8', 
		'\xE9', '\x3', '\x2', '\x2', '\x2', '\xE9', '\xEE', '\a', '\"', '\x2', 
		'\x2', '\xEA', '\xEB', '\a', '\x1C', '\x2', '\x2', '\xEB', '\xEC', '\x5', 
		'\x12', '\n', '\x2', '\xEC', '\xED', '\a', '\x1D', '\x2', '\x2', '\xED', 
		'\xEF', '\x3', '\x2', '\x2', '\x2', '\xEE', '\xEA', '\x3', '\x2', '\x2', 
		'\x2', '\xEE', '\xEF', '\x3', '\x2', '\x2', '\x2', '\xEF', '\xF8', '\x3', 
		'\x2', '\x2', '\x2', '\xF0', '\xF5', '\a', '\"', '\x2', '\x2', '\xF1', 
		'\xF2', '\a', '\x1C', '\x2', '\x2', '\xF2', '\xF3', '\x5', '\x12', '\n', 
		'\x2', '\xF3', '\xF4', '\a', '\x1D', '\x2', '\x2', '\xF4', '\xF6', '\x3', 
		'\x2', '\x2', '\x2', '\xF5', '\xF1', '\x3', '\x2', '\x2', '\x2', '\xF5', 
		'\xF6', '\x3', '\x2', '\x2', '\x2', '\xF6', '\xF8', '\x3', '\x2', '\x2', 
		'\x2', '\xF7', '\xE3', '\x3', '\x2', '\x2', '\x2', '\xF7', '\xF0', '\x3', 
		'\x2', '\x2', '\x2', '\xF8', '\xFE', '\x3', '\x2', '\x2', '\x2', '\xF9', 
		'\xFA', '\f', '\x4', '\x2', '\x2', '\xFA', '\xFB', '\a', '\x14', '\x2', 
		'\x2', '\xFB', '\xFD', '\x5', '$', '\x13', '\x5', '\xFC', '\xF9', '\x3', 
		'\x2', '\x2', '\x2', '\xFD', '\x100', '\x3', '\x2', '\x2', '\x2', '\xFE', 
		'\xFC', '\x3', '\x2', '\x2', '\x2', '\xFE', '\xFF', '\x3', '\x2', '\x2', 
		'\x2', '\xFF', '%', '\x3', '\x2', '\x2', '\x2', '\x100', '\xFE', '\x3', 
		'\x2', '\x2', '\x2', '\x101', '\x102', '\a', '\t', '\x2', '\x2', '\x102', 
		'\x103', '\x5', '\x4', '\x3', '\x2', '\x103', '\x104', '\a', '\x1C', '\x2', 
		'\x2', '\x104', '\x105', '\x5', '\x12', '\n', '\x2', '\x105', '\x106', 
		'\a', '\x1D', '\x2', '\x2', '\x106', '\x117', '\x3', '\x2', '\x2', '\x2', 
		'\x107', '\x108', '\a', '\t', '\x2', '\x2', '\x108', '\x109', '\x5', '\x4', 
		'\x3', '\x2', '\x109', '\x10A', '\a', '\x1C', '\x2', '\x2', '\x10A', '\x10B', 
		'\a', '\x1D', '\x2', '\x2', '\x10B', '\x10C', '\a', '\x18', '\x2', '\x2', 
		'\x10C', '\x111', '\x5', '\x12', '\n', '\x2', '\x10D', '\x10E', '\a', 
		'\x15', '\x2', '\x2', '\x10E', '\x110', '\x5', '\x12', '\n', '\x2', '\x10F', 
		'\x10D', '\x3', '\x2', '\x2', '\x2', '\x110', '\x113', '\x3', '\x2', '\x2', 
		'\x2', '\x111', '\x10F', '\x3', '\x2', '\x2', '\x2', '\x111', '\x112', 
		'\x3', '\x2', '\x2', '\x2', '\x112', '\x114', '\x3', '\x2', '\x2', '\x2', 
		'\x113', '\x111', '\x3', '\x2', '\x2', '\x2', '\x114', '\x115', '\a', 
		'\x1D', '\x2', '\x2', '\x115', '\x117', '\x3', '\x2', '\x2', '\x2', '\x116', 
		'\x101', '\x3', '\x2', '\x2', '\x2', '\x116', '\x107', '\x3', '\x2', '\x2', 
		'\x2', '\x117', '\'', '\x3', '\x2', '\x2', '\x2', '\x118', '\x11A', '\a', 
		'\b', '\x2', '\x2', '\x119', '\x11B', '\x5', '\x12', '\n', '\x2', '\x11A', 
		'\x119', '\x3', '\x2', '\x2', '\x2', '\x11A', '\x11B', '\x3', '\x2', '\x2', 
		'\x2', '\x11B', ')', '\x3', '\x2', '\x2', '\x2', '\x11C', '\x11D', '\x5', 
		'\x1E', '\x10', '\x2', '\x11D', '\x11E', '\a', '\x17', '\x2', '\x2', '\x11E', 
		'\x121', '\x3', '\x2', '\x2', '\x2', '\x11F', '\x121', '\x5', '\x1A', 
		'\xE', '\x2', '\x120', '\x11C', '\x3', '\x2', '\x2', '\x2', '\x120', '\x11F', 
		'\x3', '\x2', '\x2', '\x2', '\x121', '+', '\x3', '\x2', '\x2', '\x2', 
		'\x122', '\x123', '\x5', '\x1E', '\x10', '\x2', '\x123', '\x124', '\a', 
		'\x17', '\x2', '\x2', '\x124', '\x127', '\x3', '\x2', '\x2', '\x2', '\x125', 
		'\x127', '\x5', '\x1A', '\xE', '\x2', '\x126', '\x122', '\x3', '\x2', 
		'\x2', '\x2', '\x126', '\x125', '\x3', '\x2', '\x2', '\x2', '\x127', '-', 
		'\x3', '\x2', '\x2', '\x2', '\x128', '\x129', '\x5', '\n', '\x6', '\x2', 
		'\x129', '\x12A', '\a', '!', '\x2', '\x2', '\x12A', '\x12B', '\x5', '\x12', 
		'\n', '\x2', '\x12B', '\x12C', '\a', '\x17', '\x2', '\x2', '\x12C', '\x138', 
		'\x3', '\x2', '\x2', '\x2', '\x12D', '\x12E', '\x5', '\n', '\x6', '\x2', 
		'\x12E', '\x132', '\a', '\x18', '\x2', '\x2', '\x12F', '\x131', '\x5', 
		'\x10', '\t', '\x2', '\x130', '\x12F', '\x3', '\x2', '\x2', '\x2', '\x131', 
		'\x134', '\x3', '\x2', '\x2', '\x2', '\x132', '\x130', '\x3', '\x2', '\x2', 
		'\x2', '\x132', '\x133', '\x3', '\x2', '\x2', '\x2', '\x133', '\x135', 
		'\x3', '\x2', '\x2', '\x2', '\x134', '\x132', '\x3', '\x2', '\x2', '\x2', 
		'\x135', '\x136', '\a', '\x19', '\x2', '\x2', '\x136', '\x138', '\x3', 
		'\x2', '\x2', '\x2', '\x137', '\x128', '\x3', '\x2', '\x2', '\x2', '\x137', 
		'\x12D', '\x3', '\x2', '\x2', '\x2', '\x138', '/', '\x3', '\x2', '\x2', 
		'\x2', '\x139', '\x13A', '\t', '\x3', '\x2', '\x2', '\x13A', '\x31', '\x3', 
		'\x2', '\x2', '\x2', '\x13B', '\x13C', '\a', '$', '\x2', '\x2', '\x13C', 
		'\x33', '\x3', '\x2', '\x2', '\x2', '\x13D', '\x13E', '\t', '\x4', '\x2', 
		'\x2', '\x13E', '\x35', '\x3', '\x2', '\x2', '\x2', '#', ':', '\x43', 
		'H', 'O', '^', '\x61', 'n', 'q', '\x81', '\x8D', '\x91', '\x96', '\xA1', 
		'\xA4', '\xAA', '\xB2', '\xBB', '\xC3', '\xD0', '\xD7', '\xDD', '\xE7', 
		'\xEE', '\xF5', '\xF7', '\xFE', '\x111', '\x116', '\x11A', '\x120', '\x126', 
		'\x132', '\x137',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace MarlinCompiler.Antlr
